# Auto-generated draw plot script by LLMResonanceGenerator — do not edit manually

import numpy as onp
import os
import re
import json
import logging
import logging.config
import pandas as pd
import ROOT
from ROOT import TH1D, TCanvas, gStyle, TLegend, TLatex


import sys
foo_path = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(foo_path)
sys.path.append(foo_path)


def setup_logging():
    """Setup logging configuration"""
    with open("config/logconfig_plot.json", "r") as config_file:
        LOGGING_CONFIG = json.load(config_file)
        logging.config.dictConfig(LOGGING_CONFIG)
    return logging.getLogger("fit")



# === generated by LLM | cache: draw_plot_phif0_980_cache.json | hash: ec7abe18 ===
def draw_single_resonance_phif0_980(var_name, data_arr, mc_arr, all_wt, all_truth_wt, data_size):
    """画 phif0_980 共振态的 data vs fit 叠加图，返回 fit fraction。"""
    fit_result_wt = all_wt["all_mods_wt"]
    sum_wt = onp.sum(fit_result_wt)
    sum_truth_wt = onp.sum(all_truth_wt["all_mods_wt"])

    max_value = mc_arr.max() + 0.15
    min_value = mc_arr.min() - 0.15

    hist_data = TH1D("data_" + var_name, var_name + " data", 100, min_value, max_value)
    for i in range(data_arr.shape[0]):
        hist_data.Fill(data_arr[i])

    hist_fit = TH1D("fit_" + var_name, var_name + " fit", 100, min_value, max_value)
    for i in range(mc_arr.shape[0]):
        hist_fit.Fill(mc_arr[i], fit_result_wt[i])
    hist_fit.Scale(data_size / sum_wt)

    comp_wt = all_wt["phif0_kk_BW_flatte980_0"]
    hist_comp = TH1D("phif0_980_" + var_name, "phif0_980 partial wave", 100, min_value, max_value)
    for i in range(mc_arr.shape[0]):
        hist_comp.Fill(mc_arr[i], comp_wt[i])
    hist_comp.Scale(data_size / sum_wt)

    frac = onp.sum(all_truth_wt["phif0_kk_BW_flatte980_0"]) / sum_truth_wt

    os.makedirs("output/pictures/partial_mods_pictures", exist_ok=True)
    c = TCanvas("phif0_980_" + var_name, "phif0_980 " + var_name, 900, 600)
    gStyle.SetOptStat(0)
    hist_data.SetMarkerStyle(20)
    hist_data.SetMarkerSize(0.8)
    hist_data.Draw("E1")
    hist_fit.SetLineColor(ROOT.kRed)
    hist_fit.SetLineWidth(2)
    hist_fit.Draw("HIST SAME")
    hist_comp.SetLineColor(ROOT.kBlue)
    hist_comp.SetLineWidth(2)
    hist_comp.SetLineStyle(2)
    hist_comp.Draw("HIST SAME")
    legend = TLegend(0.65, 0.70, 0.92, 0.92)
    legend.AddEntry(hist_data, "Data", "ep")
    legend.AddEntry(hist_fit, "Fit total", "l")
    legend.AddEntry(hist_comp, "phif0_980", "l")
    legend.Draw()
    latex = TLatex()
    latex.SetNDC()
    latex.SetTextSize(0.03)
    latex.DrawLatex(0.15, 0.85, "fit fraction: {:.4f}".format(frac))
    c.SaveAs("output/pictures/partial_mods_pictures/phif0_980_{}.png".format(var_name))

    return frac

# === generated by LLM | cache: draw_plot_phif0_1710_cache.json | hash: 75f228d3 ===
def draw_single_resonance_phif0_1710(var_name, data_arr, mc_arr, all_wt, all_truth_wt, data_size):
    """画 phif0_1710 共振态的 data vs fit 叠加图，返回 fit fraction。"""
    fit_result_wt = all_wt["all_mods_wt"]
    sum_wt = onp.sum(fit_result_wt)
    sum_truth_wt = onp.sum(all_truth_wt["all_mods_wt"])

    max_value = mc_arr.max() + 0.15
    min_value = mc_arr.min() - 0.15

    hist_data = TH1D("data_" + var_name, var_name + " data", 100, min_value, max_value)
    for i in range(data_arr.shape[0]):
        hist_data.Fill(data_arr[i])

    hist_fit = TH1D("fit_" + var_name, var_name + " fit", 100, min_value, max_value)
    for i in range(mc_arr.shape[0]):
        hist_fit.Fill(mc_arr[i], fit_result_wt[i])
    hist_fit.Scale(data_size / sum_wt)

    comp_wt = all_wt["phif0_kk_BW_BW_0"]
    hist_comp = TH1D("phif0_1710_" + var_name, "phif0_1710 partial wave", 100, min_value, max_value)
    for i in range(mc_arr.shape[0]):
        hist_comp.Fill(mc_arr[i], comp_wt[i])
    hist_comp.Scale(data_size / sum_wt)

    frac = onp.sum(all_truth_wt["phif0_kk_BW_BW_0"]) / sum_truth_wt

    os.makedirs("output/pictures/partial_mods_pictures", exist_ok=True)
    c = TCanvas("phif0_1710_" + var_name, "phif0_1710 " + var_name, 900, 600)
    gStyle.SetOptStat(0)
    hist_data.SetMarkerStyle(20)
    hist_data.SetMarkerSize(0.8)
    hist_data.Draw("E1")
    hist_fit.SetLineColor(ROOT.kRed)
    hist_fit.SetLineWidth(2)
    hist_fit.Draw("HIST SAME")
    hist_comp.SetLineColor(ROOT.kBlue)
    hist_comp.SetLineWidth(2)
    hist_comp.SetLineStyle(2)
    hist_comp.Draw("HIST SAME")
    legend = TLegend(0.65, 0.70, 0.92, 0.92)
    legend.AddEntry(hist_data, "Data", "ep")
    legend.AddEntry(hist_fit, "Fit total", "l")
    legend.AddEntry(hist_comp, "phif0_1710", "l")
    legend.Draw()
    latex = TLatex()
    latex.SetNDC()
    latex.SetTextSize(0.03)
    latex.DrawLatex(0.15, 0.85, "fit fraction: {:.4f}".format(frac))
    c.SaveAs("output/pictures/partial_mods_pictures/phif0_1710_{}.png".format(var_name))

    return frac

# === generated by LLM | cache: draw_plot_phif2_1270_cache.json | hash: be0b38ab ===
def draw_single_resonance_phif2_1270(var_name, data_arr, mc_arr, all_wt, all_truth_wt, data_size):
    fit_result_wt = all_wt["all_mods_wt"]
    sum_wt = onp.sum(fit_result_wt)
    sum_truth_wt = onp.sum(all_truth_wt["all_mods_wt"])

    max_value = mc_arr.max() + 0.15
    min_value = mc_arr.min() - 0.15

    hist_data = TH1D("data_" + var_name, var_name + " data", 100, min_value, max_value)
    for i in range(data_arr.shape[0]):
        hist_data.Fill(data_arr[i])

    hist_fit = TH1D("fit_" + var_name, var_name + " fit", 100, min_value, max_value)
    for i in range(mc_arr.shape[0]):
        hist_fit.Fill(mc_arr[i], fit_result_wt[i])
    hist_fit.Scale(data_size / sum_wt)

    comp_wt = all_wt["phif2_kk_BW_flatte1270_0"]
    hist_comp = TH1D("phif2_1270_" + var_name, "phif2_1270 partial wave", 100, min_value, max_value)
    for i in range(mc_arr.shape[0]):
        hist_comp.Fill(mc_arr[i], comp_wt[i])
    hist_comp.Scale(data_size / sum_wt)

    frac = onp.sum(all_truth_wt["phif2_kk_BW_flatte1270_0"]) / sum_truth_wt

    os.makedirs("output/pictures/partial_mods_pictures", exist_ok=True)
    c = TCanvas("phif2_1270_" + var_name, "phif2_1270 " + var_name, 900, 600)
    gStyle.SetOptStat(0)
    hist_data.SetMarkerStyle(20)
    hist_data.SetMarkerSize(0.8)
    hist_data.Draw("E1")
    hist_fit.SetLineColor(ROOT.kRed)
    hist_fit.SetLineWidth(2)
    hist_fit.Draw("HIST SAME")
    hist_comp.SetLineColor(ROOT.kBlue)
    hist_comp.SetLineWidth(2)
    hist_comp.SetLineStyle(2)
    hist_comp.Draw("HIST SAME")
    legend = TLegend(0.65, 0.70, 0.92, 0.92)
    legend.AddEntry(hist_data, "Data", "ep")
    legend.AddEntry(hist_fit, "Fit total", "l")
    legend.AddEntry(hist_comp, "phif2_1270", "l")
    legend.Draw()
    latex = TLatex()
    latex.SetNDC()
    latex.SetTextSize(0.03)
    latex.DrawLatex(0.15, 0.85, "fit fraction: {:.4f}".format(frac))
    c.SaveAs("output/pictures/partial_mods_pictures/phif2_1270_{}.png".format(var_name))

    return frac

# === generated by LLM | cache: draw_plot_phif2_1525_cache.json | hash: ffdfb047 ===
def draw_single_resonance_phif2_1525(var_name, data_arr, mc_arr, all_wt, all_truth_wt, data_size):
    fit_result_wt = all_wt["all_mods_wt"]
    sum_wt = onp.sum(fit_result_wt)
    sum_truth_wt = onp.sum(all_truth_wt["all_mods_wt"])

    max_value = mc_arr.max() + 0.15
    min_value = mc_arr.min() - 0.15

    hist_data = TH1D("data_" + var_name, var_name + " data", 100, min_value, max_value)
    for i in range(data_arr.shape[0]):
        hist_data.Fill(data_arr[i])

    hist_fit = TH1D("fit_" + var_name, var_name + " fit", 100, min_value, max_value)
    for i in range(mc_arr.shape[0]):
        hist_fit.Fill(mc_arr[i], fit_result_wt[i])
    hist_fit.Scale(data_size / sum_wt)

    comp_wt = all_wt["phif2_kk_BW_BW_0"]
    hist_comp = TH1D("phif2_1525_" + var_name, "phif2_1525 partial wave", 100, min_value, max_value)
    for i in range(mc_arr.shape[0]):
        hist_comp.Fill(mc_arr[i], comp_wt[i])
    hist_comp.Scale(data_size / sum_wt)

    frac = onp.sum(all_truth_wt["phif2_kk_BW_BW_0"]) / sum_truth_wt

    os.makedirs("output/pictures/partial_mods_pictures", exist_ok=True)
    c = TCanvas("phif2_1525_" + var_name, "phif2_1525 " + var_name, 900, 600)
    gStyle.SetOptStat(0)
    hist_data.SetMarkerStyle(20)
    hist_data.SetMarkerSize(0.8)
    hist_data.Draw("E1")
    hist_fit.SetLineColor(ROOT.kRed)
    hist_fit.SetLineWidth(2)
    hist_fit.Draw("HIST SAME")
    hist_comp.SetLineColor(ROOT.kBlue)
    hist_comp.SetLineWidth(2)
    hist_comp.SetLineStyle(2)
    hist_comp.Draw("HIST SAME")
    legend = TLegend(0.65, 0.70, 0.92, 0.92)
    legend.AddEntry(hist_data, "Data", "ep")
    legend.AddEntry(hist_fit, "Fit total", "l")
    legend.AddEntry(hist_comp, "phif2_1525", "l")
    legend.Draw()
    latex = TLatex()
    latex.SetNDC()
    latex.SetTextSize(0.03)
    latex.DrawLatex(0.15, 0.85, "fit fraction: {:.4f}".format(frac))
    c.SaveAs("output/pictures/partial_mods_pictures/phif2_1525_{}.png".format(var_name))

    return frac

# === generated by LLM | cache: draw_plot_phif2_2150_cache.json | hash: 6bc8d017 ===
def draw_single_resonance_phif2_2150(var_name, data_arr, mc_arr, all_wt, all_truth_wt, data_size):
    fit_result_wt = all_wt["all_mods_wt"]
    sum_wt = onp.sum(fit_result_wt)
    sum_truth_wt = onp.sum(all_truth_wt["all_mods_wt"])

    max_value = mc_arr.max() + 0.15
    min_value = mc_arr.min() - 0.15

    hist_data = TH1D("data_" + var_name, var_name + " data", 100, min_value, max_value)
    for i in range(data_arr.shape[0]):
        hist_data.Fill(data_arr[i])

    hist_fit = TH1D("fit_" + var_name, var_name + " fit", 100, min_value, max_value)
    for i in range(mc_arr.shape[0]):
        hist_fit.Fill(mc_arr[i], fit_result_wt[i])
    hist_fit.Scale(data_size / sum_wt)

    comp_wt = all_wt["phif2_kk_BW_BW_1"]
    hist_comp = TH1D("phif2_2150_" + var_name, "phif2_2150 partial wave", 100, min_value, max_value)
    for i in range(mc_arr.shape[0]):
        hist_comp.Fill(mc_arr[i], comp_wt[i])
    hist_comp.Scale(data_size / sum_wt)

    frac = onp.sum(all_truth_wt["phif2_kk_BW_BW_1"]) / sum_truth_wt

    os.makedirs("output/pictures/partial_mods_pictures", exist_ok=True)
    c = TCanvas("phif2_2150_" + var_name, "phif2_2150 " + var_name, 900, 600)
    gStyle.SetOptStat(0)
    hist_data.SetMarkerStyle(20)
    hist_data.SetMarkerSize(0.8)
    hist_data.Draw("E1")
    hist_fit.SetLineColor(ROOT.kRed)
    hist_fit.SetLineWidth(2)
    hist_fit.Draw("HIST SAME")
    hist_comp.SetLineColor(ROOT.kBlue)
    hist_comp.SetLineWidth(2)
    hist_comp.SetLineStyle(2)
    hist_comp.Draw("HIST SAME")
    legend = TLegend(0.65, 0.70, 0.92, 0.92)
    legend.AddEntry(hist_data, "Data", "ep")
    legend.AddEntry(hist_fit, "Fit total", "l")
    legend.AddEntry(hist_comp, "phif2_2150", "l")
    legend.Draw()
    latex = TLatex()
    latex.SetNDC()
    latex.SetTextSize(0.03)
    latex.DrawLatex(0.15, 0.85, "fit fraction: {:.4f}".format(frac))
    c.SaveAs("output/pictures/partial_mods_pictures/phif2_2150_{}.png".format(var_name))

    return frac

# === generated by LLM | cache: draw_plot_phif2_2340_cache.json | hash: 12439f47 ===
def draw_single_resonance_phif2_2340(var_name, data_arr, mc_arr, all_wt, all_truth_wt, data_size):
    """画 phif2_2340 共振态的 data vs fit 叠加图，返回 fit fraction。"""
    fit_result_wt = all_wt["all_mods_wt"]
    sum_wt = onp.sum(fit_result_wt)
    sum_truth_wt = onp.sum(all_truth_wt["all_mods_wt"])

    max_value = mc_arr.max() + 0.15
    min_value = mc_arr.min() - 0.15

    hist_data = TH1D("data_" + var_name, var_name + " data", 100, min_value, max_value)
    for i in range(data_arr.shape[0]):
        hist_data.Fill(data_arr[i])

    hist_fit = TH1D("fit_" + var_name, var_name + " fit", 100, min_value, max_value)
    for i in range(mc_arr.shape[0]):
        hist_fit.Fill(mc_arr[i], fit_result_wt[i])
    hist_fit.Scale(data_size / sum_wt)

    comp_wt = all_wt["phif2_kk_BW_BW_2"]
    hist_comp = TH1D("phif2_2340_" + var_name, "phif2_2340 partial wave", 100, min_value, max_value)
    for i in range(mc_arr.shape[0]):
        hist_comp.Fill(mc_arr[i], comp_wt[i])
    hist_comp.Scale(data_size / sum_wt)

    frac = onp.sum(all_truth_wt["phif2_kk_BW_BW_2"]) / sum_truth_wt

    os.makedirs("output/pictures/partial_mods_pictures", exist_ok=True)
    c = TCanvas("phif2_2340_" + var_name, "phif2_2340 " + var_name, 900, 600)
    gStyle.SetOptStat(0)
    hist_data.SetMarkerStyle(20)
    hist_data.SetMarkerSize(0.8)
    hist_data.Draw("E1")
    hist_fit.SetLineColor(ROOT.kRed)
    hist_fit.SetLineWidth(2)
    hist_fit.Draw("HIST SAME")
    hist_comp.SetLineColor(ROOT.kBlue)
    hist_comp.SetLineWidth(2)
    hist_comp.SetLineStyle(2)
    hist_comp.Draw("HIST SAME")
    legend = TLegend(0.65, 0.70, 0.92, 0.92)
    legend.AddEntry(hist_data, "Data", "ep")
    legend.AddEntry(hist_fit, "Fit total", "l")
    legend.AddEntry(hist_comp, "phif2_2340", "l")
    legend.Draw()
    latex = TLatex()
    latex.SetNDC()
    latex.SetTextSize(0.03)
    latex.DrawLatex(0.15, 0.85, "fit fraction: {:.4f}".format(frac))
    c.SaveAs("output/pictures/partial_mods_pictures/phif2_2340_{}.png".format(var_name))

    return frac

# === generated by LLM | cache: draw_plot_phif0_2470_cache.json | hash: 63db76c5 ===
def draw_single_resonance_phif0_2470(var_name, data_arr, mc_arr, all_wt, all_truth_wt, data_size):
    fit_result_wt = all_wt["all_mods_wt"]
    sum_wt = onp.sum(fit_result_wt)
    sum_truth_wt = onp.sum(all_truth_wt["all_mods_wt"])

    max_value = mc_arr.max() + 0.15
    min_value = mc_arr.min() - 0.15

    hist_data = TH1D("data_" + var_name, var_name + " data", 100, min_value, max_value)
    for i in range(data_arr.shape[0]):
        hist_data.Fill(data_arr[i])

    hist_fit = TH1D("fit_" + var_name, var_name + " fit", 100, min_value, max_value)
    for i in range(mc_arr.shape[0]):
        hist_fit.Fill(mc_arr[i], fit_result_wt[i])
    hist_fit.Scale(data_size / sum_wt)

    comp_wt = all_wt["phif0_kk_BW_BW_1"]
    hist_comp = TH1D("phif0_2470_" + var_name, "phif0_2470 partial wave", 100, min_value, max_value)
    for i in range(mc_arr.shape[0]):
        hist_comp.Fill(mc_arr[i], comp_wt[i])
    hist_comp.Scale(data_size / sum_wt)

    frac = onp.sum(all_truth_wt["phif0_kk_BW_BW_1"]) / sum_truth_wt

    os.makedirs("output/pictures/partial_mods_pictures", exist_ok=True)
    c = TCanvas("phif0_2470_" + var_name, "phif0_2470 " + var_name, 900, 600)
    gStyle.SetOptStat(0)
    hist_data.SetMarkerStyle(20)
    hist_data.SetMarkerSize(0.8)
    hist_data.Draw("E1")
    hist_fit.SetLineColor(ROOT.kRed)
    hist_fit.SetLineWidth(2)
    hist_fit.Draw("HIST SAME")
    hist_comp.SetLineColor(ROOT.kBlue)
    hist_comp.SetLineWidth(2)
    hist_comp.SetLineStyle(2)
    hist_comp.Draw("HIST SAME")
    legend = TLegend(0.65, 0.70, 0.92, 0.92)
    legend.AddEntry(hist_data, "Data", "ep")
    legend.AddEntry(hist_fit, "Fit total", "l")
    legend.AddEntry(hist_comp, "phif0_2470", "l")
    legend.Draw()
    latex = TLatex()
    latex.SetNDC()
    latex.SetTextSize(0.03)
    latex.DrawLatex(0.15, 0.85, "fit fraction: {:.4f}".format(frac))
    c.SaveAs("output/pictures/partial_mods_pictures/phif0_2470_{}.png".format(var_name))

    return frac

# === generated by LLM | cache: draw_plot_K2100_cache.json | hash: 8563eb57 ===
def draw_single_resonance_K2100(var_name, data_arr, mc_arr, all_wt, all_truth_wt, data_size):
    """画 K2100 共振态的 data vs fit 叠加图，返回 fit fraction。"""
    fit_result_wt = all_wt["all_mods_wt"]
    sum_wt = onp.sum(fit_result_wt)
    sum_truth_wt = onp.sum(all_truth_wt["all_mods_wt"])

    max_value = mc_arr.max() + 0.15
    min_value = mc_arr.min() - 0.15

    hist_data = TH1D("data_" + var_name, var_name + " data", 100, min_value, max_value)
    for i in range(data_arr.shape[0]):
        hist_data.Fill(data_arr[i])

    hist_fit = TH1D("fit_" + var_name, var_name + " fit", 100, min_value, max_value)
    for i in range(mc_arr.shape[0]):
        hist_fit.Fill(mc_arr[i], fit_result_wt[i])
    hist_fit.Scale(data_size / sum_wt)

    comp_wt = all_wt["u_kst2_r_kk_BW_BW_0"]
    hist_comp = TH1D("K2100_" + var_name, "K2100 partial wave", 100, min_value, max_value)
    for i in range(mc_arr.shape[0]):
        hist_comp.Fill(mc_arr[i], comp_wt[i])
    hist_comp.Scale(data_size / sum_wt)

    frac = onp.sum(all_truth_wt["u_kst2_r_kk_BW_BW_0"]) / sum_truth_wt

    os.makedirs("output/pictures/partial_mods_pictures", exist_ok=True)
    c = TCanvas("K2100_" + var_name, "K2100 " + var_name, 900, 600)
    gStyle.SetOptStat(0)
    hist_data.SetMarkerStyle(20)
    hist_data.SetMarkerSize(0.8)
    hist_data.Draw("E1")
    hist_fit.SetLineColor(ROOT.kRed)
    hist_fit.SetLineWidth(2)
    hist_fit.Draw("HIST SAME")
    hist_comp.SetLineColor(ROOT.kBlue)
    hist_comp.SetLineWidth(2)
    hist_comp.SetLineStyle(2)
    hist_comp.Draw("HIST SAME")
    legend = TLegend(0.65, 0.70, 0.92, 0.92)
    legend.AddEntry(hist_data, "Data", "ep")
    legend.AddEntry(hist_fit, "Fit total", "l")
    legend.AddEntry(hist_comp, "K2100", "l")
    legend.Draw()
    latex = TLatex()
    latex.SetNDC()
    latex.SetTextSize(0.03)
    latex.DrawLatex(0.15, 0.85, "fit fraction: {:.4f}".format(frac))
    c.SaveAs("output/pictures/partial_mods_pictures/K2100_{}.png".format(var_name))

    return frac

# === generated by LLM | cache: draw_plot_K1820_cache.json | hash: ae38f7be ===
def draw_single_resonance_K1820(var_name, data_arr, mc_arr, all_wt, all_truth_wt, data_size):
    """画 K1820 共振态的 data vs fit 叠加图，返回 fit fraction。"""
    fit_result_wt = all_wt["all_mods_wt"]
    sum_wt = onp.sum(fit_result_wt)
    sum_truth_wt = onp.sum(all_truth_wt["all_mods_wt"])

    max_value = mc_arr.max() + 0.15
    min_value = mc_arr.min() - 0.15

    hist_data = TH1D("data_" + var_name, var_name + " data", 100, min_value, max_value)
    for i in range(data_arr.shape[0]):
        hist_data.Fill(data_arr[i])

    hist_fit = TH1D("fit_" + var_name, var_name + " fit", 100, min_value, max_value)
    for i in range(mc_arr.shape[0]):
        hist_fit.Fill(mc_arr[i], fit_result_wt[i])
    hist_fit.Scale(data_size / sum_wt)

    comp_wt = all_wt["u_kst2_r_kk_BW_BW_0"]
    hist_comp = TH1D("K1820_" + var_name, "K1820 partial wave", 100, min_value, max_value)
    for i in range(mc_arr.shape[0]):
        hist_comp.Fill(mc_arr[i], comp_wt[i])
    hist_comp.Scale(data_size / sum_wt)

    frac = onp.sum(all_truth_wt["u_kst2_r_kk_BW_BW_0"]) / sum_truth_wt

    os.makedirs("output/pictures/partial_mods_pictures", exist_ok=True)
    c = TCanvas("K1820_" + var_name, "K1820 " + var_name, 900, 600)
    gStyle.SetOptStat(0)
    hist_data.SetMarkerStyle(20)
    hist_data.SetMarkerSize(0.8)
    hist_data.Draw("E1")
    hist_fit.SetLineColor(ROOT.kRed)
    hist_fit.SetLineWidth(2)
    hist_fit.Draw("HIST SAME")
    hist_comp.SetLineColor(ROOT.kBlue)
    hist_comp.SetLineWidth(2)
    hist_comp.SetLineStyle(2)
    hist_comp.Draw("HIST SAME")
    legend = TLegend(0.65, 0.70, 0.92, 0.92)
    legend.AddEntry(hist_data, "Data", "ep")
    legend.AddEntry(hist_fit, "Fit total", "l")
    legend.AddEntry(hist_comp, "K1820", "l")
    legend.Draw()
    latex = TLatex()
    latex.SetNDC()
    latex.SetTextSize(0.03)
    latex.DrawLatex(0.15, 0.85, "fit fraction: {:.4f}".format(frac))
    c.SaveAs("output/pictures/partial_mods_pictures/K1820_{}.png".format(var_name))

    return frac

# === generated by LLM | cache: draw_plot_K2250_cache.json | hash: ac6c3ede ===
def draw_single_resonance_K2250(var_name, data_arr, mc_arr, all_wt, all_truth_wt, data_size):
    """画 K2250 共振态的 data vs fit 叠加图，返回 fit fraction。"""
    fit_result_wt = all_wt["all_mods_wt"]
    sum_wt = onp.sum(fit_result_wt)
    sum_truth_wt = onp.sum(all_truth_wt["all_mods_wt"])

    max_value = mc_arr.max() + 0.15
    min_value = mc_arr.min() - 0.15

    hist_data = TH1D("data_" + var_name, var_name + " data", 100, min_value, max_value)
    for i in range(data_arr.shape[0]):
        hist_data.Fill(data_arr[i])

    hist_fit = TH1D("fit_" + var_name, var_name + " fit", 100, min_value, max_value)
    for i in range(mc_arr.shape[0]):
        hist_fit.Fill(mc_arr[i], fit_result_wt[i])
    hist_fit.Scale(data_size / sum_wt)

    comp_wt = all_wt["u_kst2_r_kk_BW_BW_0"]
    hist_comp = TH1D("K2250_" + var_name, "K2250 partial wave", 100, min_value, max_value)
    for i in range(mc_arr.shape[0]):
        hist_comp.Fill(mc_arr[i], comp_wt[i])
    hist_comp.Scale(data_size / sum_wt)

    frac = onp.sum(all_truth_wt["u_kst2_r_kk_BW_BW_0"]) / sum_truth_wt

    os.makedirs("output/pictures/partial_mods_pictures", exist_ok=True)
    c = TCanvas("K2250_" + var_name, "K2250 " + var_name, 900, 600)
    gStyle.SetOptStat(0)
    hist_data.SetMarkerStyle(20)
    hist_data.SetMarkerSize(0.8)
    hist_data.Draw("E1")
    hist_fit.SetLineColor(ROOT.kRed)
    hist_fit.SetLineWidth(2)
    hist_fit.Draw("HIST SAME")
    hist_comp.SetLineColor(ROOT.kBlue)
    hist_comp.SetLineWidth(2)
    hist_comp.SetLineStyle(2)
    hist_comp.Draw("HIST SAME")
    legend = TLegend(0.65, 0.70, 0.92, 0.92)
    legend.AddEntry(hist_data, "Data", "ep")
    legend.AddEntry(hist_fit, "Fit total", "l")
    legend.AddEntry(hist_comp, "K2250", "l")
    legend.Draw()
    latex = TLatex()
    latex.SetNDC()
    latex.SetTextSize(0.03)
    latex.DrawLatex(0.15, 0.85, "fit fraction: {:.4f}".format(frac))
    c.SaveAs("output/pictures/partial_mods_pictures/K2250_{}.png".format(var_name))

    return frac

# === generated by LLM | cache: draw_plot_main_cache.json | hash: 06b36867 ===
if __name__ == "__main__":
    ROOT.gROOT.SetBatch(True)
    logger = setup_logging()
    os.makedirs("output/pictures/partial_mods_pictures", exist_ok=True)

    all_wt = onp.load("output/draw/weight.npz")
    all_truth_wt = onp.load("output/draw/weight_truth.npz")

    data_phi_kk = onp.sqrt(onp.load("data/real_data/phi_kk.npy"))
    mc_phi_kk = onp.sqrt(onp.load("data/mc_truth/phi_kk.npy"))
    data_f_kk = onp.sqrt(onp.load("data/real_data/f_kk.npy"))
    mc_f_kk = onp.sqrt(onp.load("data/mc_truth/f_kk.npy"))
    data_kst2_124_kk = onp.sqrt(onp.load("data/real_data/kst2_124_kk.npy"))
    mc_kst2_124_kk = onp.sqrt(onp.load("data/mc_truth/kst2_124_kk.npy"))
    data_kst2_123_kk = onp.sqrt(onp.load("data/real_data/kst2_123_kk.npy"))
    mc_kst2_123_kk = onp.sqrt(onp.load("data/mc_truth/kst2_123_kk.npy"))
    data_b123_kk = onp.sqrt(onp.load("data/real_data/b123_kk.npy"))
    mc_b123_kk = onp.sqrt(onp.load("data/mc_truth/b123_kk.npy"))
    data_b124_kk = onp.sqrt(onp.load("data/real_data/b124_kk.npy"))
    mc_b124_kk = onp.sqrt(onp.load("data/mc_truth/b124_kk.npy"))

    draw_funcs = [
        ("phif0_980", draw_single_resonance_phif0_980),
        ("phif0_1710", draw_single_resonance_phif0_1710),
        ("phif2_1270", draw_single_resonance_phif2_1270),
        ("phif2_1525", draw_single_resonance_phif2_1525),
        ("phif2_2150", draw_single_resonance_phif2_2150),
        ("phif2_2340", draw_single_resonance_phif2_2340),
        ("phif0_2470", draw_single_resonance_phif0_2470),
        ("K2100", draw_single_resonance_K2100),
        ("K1820", draw_single_resonance_K1820),
        ("K2250", draw_single_resonance_K2250),
    ]

    fit_fraction_coll = []

    for var_name, data_arr, mc_arr in [
        ("f_kk", data_f_kk, mc_f_kk),
        ("phi_kk", data_phi_kk, mc_phi_kk),
        ("kst2_124_kk", data_kst2_124_kk, mc_kst2_124_kk),
        ("kst2_123_kk", data_kst2_123_kk, mc_kst2_123_kk),
    ]:
        data_size = data_arr.shape[0]
        for mod_name, draw_func in draw_funcs:
            frac = draw_func(var_name, data_arr, mc_arr, all_wt, all_truth_wt, data_size)
            if var_name == "f_kk":
                fit_fraction_coll.append({"mod_name": mod_name, "var": var_name, "fraction": float(frac)})

    for var_name, data_arr, mc_arr in [
        ("b123_kk", data_b123_kk, mc_b123_kk),
        ("b124_kk", data_b124_kk, mc_b124_kk),
    ]:
        doubled_wt = {key: onp.append(all_wt[key], all_wt[key]) for key in all_wt.files}
        doubled_truth_wt = {key: onp.append(all_truth_wt[key], all_truth_wt[key]) for key in all_truth_wt.files}
        base_size = all_wt["all_mods_wt"].shape[0]
        doubled_mc = onp.append(mc_arr[:base_size], mc_arr[:base_size])
        data_size = data_arr.shape[0]
        for mod_name, draw_func in draw_funcs:
            draw_func(var_name, data_arr, doubled_mc, doubled_wt, doubled_truth_wt, data_size)

    os.makedirs("output/draw", exist_ok=True)
    with open("output/draw/fit_fraction_table.json", "w") as f:
        json.dump(fit_fraction_coll, f, indent=2)
    df = pd.DataFrame(fit_fraction_coll)
    with open("output/draw/fit_fraction_table.md", "w") as f:
        f.write(df.to_markdown())
    with open("output/draw/fit_fraction_table.latex", "w") as f:
        f.write(df.to_latex(escape=False))
    logger.info("画图完成，结果已保存至 output/pictures/partial_mods_pictures/")