# Auto-generated draw weight script by LLMResonanceGenerator — do not edit manually
import copy
import json
import logging
import logging.config
import os
# must set before importing jax
os.environ["XLA_PYTHON_CLIENT_PREALLOCATE"] = "false"
import time
import numpy as onp
from functools import partial
from scipy.optimize import minimize

import jax.numpy as np
from jax import device_put, grad, jit, vmap, jvp
from jax import config



import sys
foo_path = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(foo_path)
sys.path.append(foo_path)



def setup_logging():
    """Setup logging configuration"""
    with open("config/logconfig_fit.json", "r") as config_file:
        LOGGING_CONFIG = json.load(config_file)
        logging.config.dictConfig(LOGGING_CONFIG)
    return logging.getLogger("fit")



def dplex_deinsum(subscript, aa, bb):
    real = np.einsum(subscript, aa[0], bb[0]) - np.einsum(subscript, aa[1], bb[1])
    imag = np.einsum(subscript, aa[0], bb[1]) + np.einsum(subscript, aa[1], bb[0])
    return np.stack([real, imag], axis=0)

def dplex_deinsum_ord(subscript, aa, bb):
    real = np.einsum(subscript, aa, bb[0])
    imag = np.einsum(subscript, aa, bb[1])
    return np.stack([real, imag], axis=0)

def dplex_dabs(aa):
    return aa[0]**2 + aa[1]**2 # 因为是纵向叠加所以aa[0]是纵向上第一个数组

def dplex_dtomine(aa):
    return np.stack([np.real(aa), np.imag(aa)], axis=0) # 组合而成的数组 axis=0 的第一个数组为实部，第二个数组为虚部

def dplex_dconstruct(aa, bb):
    return np.stack([aa, bb], axis=0) # 纵向叠加数组 第一维为实部，第二维为虚部

def dplex_ddivide(a, bb):
    real = a * bb[0] / dplex_dabs(bb)
    imag = -a * bb[1] / dplex_dabs(bb)
    return np.stack([real, imag], axis=0)


#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# ==============================================================================
# SECTION: PHYSICS_FUNCTIONS
# Physics calculation functions (resonance shape functions)
# Provided by the user for each analysis. Copy this file to your analysis
# directory as physics_functions.py and keep only the functions you need.
# ==============================================================================

import jax.numpy as np


def BW(m_, w_, Sbc):
    l = (Sbc.shape)[0]
    temp = dplex_dconstruct(m_*m_ - Sbc, -m_*w_*np.ones(l))
    return dplex_ddivide(1.0, temp)


def BW_relativity(m_, w_, Sbc):
    gamma = np.sqrt(m_*m_*(m_*m_+w_*w_))
    k = np.sqrt(2*np.sqrt(2)*m_*np.abs(w_)*gamma/np.pi/np.sqrt(m_*m_+gamma))
    l = (Sbc.shape)[0]
    temp = dplex_dconstruct(m_*m_ - Sbc, -m_*w_*np.ones(l))
    return dplex_ddivide(k, temp)


def flatte980(m_, g_pipi, rg, Sbc):
    g_kk = rg * g_pipi
    m_k = 0.493677
    m_pi = 0.13957061
    rho_kk = np.sqrt(np.abs(1 - 4*m_k*m_k / Sbc))
    rho_pipi = np.sqrt(np.abs(1 - 4*m_pi*m_pi / Sbc))
    tmp_A = dplex_dconstruct(m_**2 - Sbc, -1*(g_pipi*rho_pipi + g_kk*rho_kk))
    return dplex_ddivide(1.0, tmp_A)


def flatte1270(m_, w_, Sbc):
    rm = m_ * m_
    gr = m_ * w_
    q2r = 0.25 * rm - 0.0194792
    b2r = q2r * (q2r + 0.1825) + 0.033306
    g11270 = gr * b2r / np.power(q2r, 2.5)
    q2 = 0.25 * Sbc - 0.0194792
    b2 = q2 * (q2 + 0.1825) + 0.033306
    g1 = g11270 * np.power(q2, 2.5) / b2
    tmp = dplex_dconstruct(Sbc - rm, g1)
    return dplex_ddivide(gr, tmp)


def flatte500(m_, b1, b2, b3, b4, b5, Sbc):
    m2 = m_*m_
    rp = 0.139556995
    mpi2d2 = 0.009739946882
    cro1 = np.sqrt(np.abs((Sbc-(2*rp)**2)*Sbc))/Sbc
    cro2 = np.sqrt(np.abs((m2-(2*rp)**2)*m2))/m2
    pip1 = np.sqrt(np.abs(1.0 - 0.3116765584/Sbc))/(1.0+np.exp(9.8-3.5*Sbc))
    pip2 = np.sqrt(np.abs(1.0 - 0.3116765584/m2))/(1.0+np.exp(9.8-3.5*m2))
    cgam1 = m_*(b1+b2*Sbc)*(Sbc-mpi2d2)/(m2-mpi2d2)*np.exp(-(Sbc-m2)/b3)*cro1/cro2
    cgam2 = m_*b4*pip1/pip2
    tmp = dplex_dconstruct(m2-Sbc, -b5*(cgam1+cgam2))
    return dplex_ddivide(1.0, tmp)


# === generated by LLM | cache: draw_load_data_cache.json | hash: a7aef568 ===
def load_data():
    data = {}

    # Load MC evaluation sample for fitted-weight histograms
    data['data_phi_kk'] = onp.load("data/mc_truth/phi_kk.npy")

    # Load MC data
    data['mc_phi_kk'] = onp.load("data/mc_truth/phi_kk.npy")

    # MC truth data (for constraints)
    data['truth_phi_kk'] = data['mc_phi_kk'][0:150000]

    # Load MC evaluation sample for fitted-weight histograms
    data['data_f_kk'] = onp.load("data/mc_truth/f_kk.npy")

    # Load MC data
    data['mc_f_kk'] = onp.load("data/mc_truth/f_kk.npy")

    # MC truth data (for constraints)
    data['truth_f_kk'] = data['mc_f_kk'][0:150000]

    # Load MC evaluation sample for fitted-weight histograms
    data['data_kst2_124_kk'] = onp.load("data/mc_truth/kst2_124_kk.npy")

    # Load MC data
    data['mc_kst2_124_kk'] = onp.load("data/mc_truth/kst2_124_kk.npy")

    # MC truth data (for constraints)
    data['truth_kst2_124_kk'] = data['mc_kst2_124_kk'][0:150000]

    # Load MC evaluation sample for fitted-weight histograms
    data['data_kst2_123_kk'] = onp.load("data/mc_truth/kst2_123_kk.npy")

    # Load MC data
    data['mc_kst2_123_kk'] = onp.load("data/mc_truth/kst2_123_kk.npy")

    # MC truth data (for constraints)
    data['truth_kst2_123_kk'] = data['mc_kst2_123_kk'][0:150000]

    # Load MC evaluation sample for fitted-weight histograms
    data['data_phif0_kk'] = onp.load("data/mc_truth/phif0_kk.npy")

    # Load MC data
    data['mc_phif0_kk'] = onp.load("data/mc_truth/phif0_kk.npy")

    # MC truth data (for constraints)
    data['truth_phif0_kk'] = data['mc_phif0_kk'][:, 0:150000]

    # Load MC evaluation sample for fitted-weight histograms
    data['data_phif2_kk'] = onp.load("data/mc_truth/phif2_kk.npy")

    # Load MC data
    data['mc_phif2_kk'] = onp.load("data/mc_truth/phif2_kk.npy")

    # MC truth data (for constraints)
    data['truth_phif2_kk'] = data['mc_phif2_kk'][:, 0:150000]

    # Load MC evaluation sample for fitted-weight histograms
    data['data_u_kst2_r_kk'] = onp.load("data/mc_truth/u_kst2_r_kk.npy")

    # Load MC data
    data['mc_u_kst2_r_kk'] = onp.load("data/mc_truth/u_kst2_r_kk.npy")

    # MC truth data (for constraints)
    data['truth_u_kst2_r_kk'] = data['mc_u_kst2_r_kk'][:, 0:150000]

    # Load MC evaluation sample for fitted-weight histograms
    data['data_u_kst2_l_kk'] = onp.load("data/mc_truth/u_kst2_l_kk.npy")

    # Load MC data
    data['mc_u_kst2_l_kk'] = onp.load("data/mc_truth/u_kst2_l_kk.npy")

    # MC truth data (for constraints)
    data['truth_u_kst2_l_kk'] = data['mc_u_kst2_l_kk'][:, 0:150000]

    # Extra Sbc data (1D kinematic variables, no normalization needed)
    data['data_b123_kk'] = onp.load("data/mc_truth/b123_kk.npy")
    data['mc_b123_kk'] = onp.load("data/mc_truth/b123_kk.npy")
    data['truth_b123_kk'] = data['mc_b123_kk'][0:150000]

    # Extra Sbc data (1D kinematic variables, no normalization needed)
    data['data_b124_kk'] = onp.load("data/mc_truth/b124_kk.npy")
    data['mc_b124_kk'] = onp.load("data/mc_truth/b124_kk.npy")
    data['truth_b124_kk'] = data['mc_b124_kk'][0:150000]

    return data

def normalize_data(data):
    # 计算归一化因子
    regular_phif0_kk = 1. / onp.average(
        onp.sqrt(onp.sum(onp.asarray(data['mc_phif0_kk'])**2, axis=2)), axis=1
    )
    regular_phif2_kk = 1. / onp.average(
        onp.sqrt(onp.sum(onp.asarray(data['mc_phif2_kk'])**2, axis=2)), axis=1
    )
    regular_u_kst2_r_kk = 1. / onp.average(
        onp.sqrt(onp.sum(onp.asarray(data['mc_u_kst2_r_kk'])**2, axis=2)), axis=1
    )
    regular_u_kst2_l_kk = 1. / onp.average(
        onp.sqrt(onp.sum(onp.asarray(data['mc_u_kst2_l_kk'])**2, axis=2)), axis=1
    )

    # 应用归一化
    data['data_phif0_kk'] = onp.einsum("jkl,j->jkl", data['data_phif0_kk'], regular_phif0_kk)
    data['mc_phif0_kk'] = onp.einsum("jkl,j->jkl", data['mc_phif0_kk'], regular_phif0_kk)
    data['truth_phif0_kk'] = onp.einsum("jkl,j->jkl", data['truth_phif0_kk'], regular_phif0_kk)

    data['data_phif2_kk'] = onp.einsum("jkl,j->jkl", data['data_phif2_kk'], regular_phif2_kk)
    data['mc_phif2_kk'] = onp.einsum("jkl,j->jkl", data['mc_phif2_kk'], regular_phif2_kk)
    data['truth_phif2_kk'] = onp.einsum("jkl,j->jkl", data['truth_phif2_kk'], regular_phif2_kk)

    data['data_u_kst2_r_kk'] = onp.einsum("jkl,j->jkl", data['data_u_kst2_r_kk'], regular_u_kst2_r_kk)
    data['mc_u_kst2_r_kk'] = onp.einsum("jkl,j->jkl", data['mc_u_kst2_r_kk'], regular_u_kst2_r_kk)
    data['truth_u_kst2_r_kk'] = onp.einsum("jkl,j->jkl", data['truth_u_kst2_r_kk'], regular_u_kst2_r_kk)

    data['data_u_kst2_l_kk'] = onp.einsum("jkl,j->jkl", data['data_u_kst2_l_kk'], regular_u_kst2_l_kk)
    data['mc_u_kst2_l_kk'] = onp.einsum("jkl,j->jkl", data['mc_u_kst2_l_kk'], regular_u_kst2_l_kk)
    data['truth_u_kst2_l_kk'] = onp.einsum("jkl,j->jkl", data['truth_u_kst2_l_kk'], regular_u_kst2_l_kk)

    return data

def prepare_data_for_jax(data, device=None):
    jax_data = {}
    for key, value in data.items():
        jax_data[key] = device_put(np.array(value), device=device)
    return jax_data

# === generated by LLM | cache: resonance_calculation_BW_flatte980.json | hash: 4d4f4a7b ===
def calculate_BW_flatte980(A_mass, A_width, phi_kk, B_mass, B_g_kk, B_rg, f_kk, Amplitude_param_AMP, Amplitude_param_const, Amplitude_param_theta):
    A_propagator = BW(A_mass, A_width, phi_kk)
    B_propagator = flatte980(B_mass, B_g_kk, B_rg, f_kk)
    propagator_combined = dplex_deinsum("j, j->j", A_propagator, B_propagator)
    const_ph = dplex_dconstruct(Amplitude_param_const, Amplitude_param_theta)
    result = dplex_deinsum_ord("ijk,li->ljk", Amplitude_param_AMP, const_ph)
    result = dplex_deinsum("ljk,j->jk", result, propagator_combined)
    return result

def component_BW_flatte980(A_mass, A_width, phi_kk, B_mass, B_g_kk, B_rg, f_kk, Amplitude_param_AMP, Amplitude_param_const, Amplitude_param_theta):
    A_propagator = BW(A_mass, A_width, phi_kk)
    B_propagator = flatte980(B_mass, B_g_kk, B_rg, f_kk)
    propagator_combined = dplex_deinsum("j, j->j", A_propagator, B_propagator)
    const_ph = dplex_dconstruct(Amplitude_param_const, Amplitude_param_theta)
    result = dplex_deinsum_ord("ijk,li->ljk", Amplitude_param_AMP, const_ph)
    result = dplex_deinsum("ljk,j->ljk", result, propagator_combined)
    return result

# === generated by LLM | cache: resonance_calculation_BW_BW.json | hash: 5e7769f4 ===
def calculate_BW_BW(A_mass, A_width, phi_kk, B_mass, B_width, f_kk, Amplitude_param_AMP, Amplitude_param_const, Amplitude_param_theta):
    A_propagator = BW(A_mass, A_width, phi_kk)
    B_propagator = np.moveaxis(
        vmap(partial(BW, Sbc=f_kk))(B_mass, B_width), 1, 0
    )
    propagator_combined = dplex_deinsum("j, ij->ij", A_propagator, B_propagator)
    const_ph = dplex_dconstruct(Amplitude_param_const, Amplitude_param_theta)
    result = dplex_deinsum_ord("ijk,li->ljk", Amplitude_param_AMP, const_ph)
    result = dplex_deinsum("ljk,lj->jk", result, propagator_combined)
    return result

def component_BW_BW(A_mass, A_width, phi_kk, B_mass, B_width, f_kk, Amplitude_param_AMP, Amplitude_param_const, Amplitude_param_theta):
    A_propagator = BW(A_mass, A_width, phi_kk)
    B_propagator = np.moveaxis(
        vmap(partial(BW, Sbc=f_kk))(B_mass, B_width), 1, 0
    )
    propagator_combined = dplex_deinsum("j, ij->ij", A_propagator, B_propagator)
    const_ph = dplex_dconstruct(Amplitude_param_const, Amplitude_param_theta)
    result = dplex_deinsum_ord("ijk,li->ljk", Amplitude_param_AMP, const_ph)
    result = dplex_deinsum("ljk,lj->ljk", result, propagator_combined)
    return result

# === generated by LLM | cache: resonance_calculation_BW_flatte1270.json | hash: 13e70978 ===
def calculate_BW_flatte1270(A_mass, A_width, phi_kk, B_mass, B_width, f_kk, Amplitude_param_AMP, Amplitude_param_const, Amplitude_param_theta):
    A_propagator = BW(A_mass, A_width, phi_kk)
    B_propagator = flatte1270(B_mass, B_width, f_kk)
    propagator_combined = dplex_deinsum("j, j->j", A_propagator, B_propagator)
    const_ph = dplex_dconstruct(Amplitude_param_const, Amplitude_param_theta)
    result = dplex_deinsum_ord("ijk,li->ljk", Amplitude_param_AMP, const_ph)
    result = dplex_deinsum("ljk,j->jk", result, propagator_combined)
    return result

def component_BW_flatte1270(A_mass, A_width, phi_kk, B_mass, B_width, f_kk, Amplitude_param_AMP, Amplitude_param_const, Amplitude_param_theta):
    A_propagator = BW(A_mass, A_width, phi_kk)
    B_propagator = flatte1270(B_mass, B_width, f_kk)
    propagator_combined = dplex_deinsum("j, j->j", A_propagator, B_propagator)
    const_ph = dplex_dconstruct(Amplitude_param_const, Amplitude_param_theta)
    result = dplex_deinsum_ord("ijk,li->ljk", Amplitude_param_AMP, const_ph)
    result = dplex_deinsum("ljk,j->ljk", result, propagator_combined)
    return result

# === generated by LLM | cache: extract_parameters_cache.json | hash: b124373b ===
args_list = onp.array([
    0.9794812115574156, 0.10678616326827592, 8.570187550432664,
    0.1065182971468388, 0.03807025376236671,
    1.6761965590304995, 2.57497529295397,
    0.16270071108440043, 0.15761784400243628,
    0.02201375198386279, 0.007433204877151768,
    -0.345074426966773, -0.15428119408751656,
    0.008302300118288414, -0.018544178045626723,
    0.2290031973516395, -0.13412740539296167,
    1.2896149318644679, 0.1959796900380022,
    -0.013533706721054747, -0.01650921272412254, 0.015339403283337268,
    0.029798824827026338, 0.020982478502465995,
    0.05458389002821978, 0.016032334798079934, 0.017179622009723918,
    -0.050143087437086675, -0.008718872479379924,
    1.5222602842746435, 2.1619576785269476, 2.547889297662712,
    0.08576525399315078, 0.15906049251159413, 0.324001266488012,
    -0.005345214125595505, 0.0031770703345810553, -0.0036743677603351056,
    0.004813366936315499, 0.010000673114238258,
    0.004643720949518616, -0.0009682564746806725, -0.0029804674908844213,
    0.008315390493289363, 0.0005819695034846763,
    -0.15266341362240637, -0.05030214288962155, -0.01856511044577769,
    0.0908719088071242, 0.029544599934778714,
    -0.010529063356530807, 0.003910028530572422, 0.0031787953173277725,
    0.0333658928584713, -0.006053516058970728,
    0.00545992748088964, -0.012498776031677225, 0.002196563552197887,
    -0.016814307435916394, -0.007232946300343621,
    0.06277085590848677, -0.0031366601030189344, 0.13756083806604205,
    -0.0033564526519642953, 0.06849361819185686,
    2.0945745764239794, 1.8192837147853098, 2.228180871519652,
    0.1111549213189184, 0.2552907595714486, 0.22526773581883117,
    0.00668002974985798, 0.004965565274392332,
    0.05353392339205181, -0.013515632832936594,
    -0.021627369735391727, 0.0034149684028485067,
    -0.014345480981877965, -0.004182231968927211,
    -0.029170417788916315, 0.008796315351616747,
    -0.03739773648153083, 0.005079738018594662
])

def extract_parameters(args):
    """提取所有物理参数的公共函数"""
    return {
        'phi_mass': np.array([1.02]),
        'phi_width': np.array([0.004]),
        'f980_mass': np.array([args[0]]),
        'f980_g_kk': np.array([args[1]]),
        'f980_rg': np.array([args[2]]),
        'f980_const': np.array([0.1, args[3]]).reshape(-1, 2),
        'f980_theta': np.array([0.1, args[4]]).reshape(-1, 2),
        'f0_mass': np.array([args[5], args[6]]),
        'f0_width': np.array([args[7], args[8]]),
        'f0_const': np.array([args[9], args[10], args[11], args[12]]).reshape(-1, 2),
        'f0_theta': np.array([args[13], args[14], args[15], args[16]]).reshape(-1, 2),
        'f1270_mass': np.array([args[17]]),
        'f1270_width': np.array([args[18]]),
        'f1270_const': np.array([args[19], args[20], args[21], args[22], args[23]]).reshape(-1, 5),
        'f1270_theta': np.array([args[24], args[25], args[26], args[27], args[28]]).reshape(-1, 5),
        'f2_mass': np.array([args[29], args[30], args[31]]),
        'f2_width': np.array([args[32], args[33], args[34]]),
        'f2_const': np.array([args[35], args[36], args[37], args[38], args[39],
                               args[40], args[41], args[42], args[43], args[44],
                               args[45], args[46], args[47], args[48], args[49]]).reshape(-1, 5),
        'f2_theta': np.array([args[50], args[51], args[52], args[53], args[54],
                               args[55], args[56], args[57], args[58], args[59],
                               args[60], args[61], args[62], args[63], args[64]]).reshape(-1, 5),
        'kst2_mass': np.array([args[65], args[66], args[67]]),
        'kst2_width': np.array([args[68], args[69], args[70]]),
        'kst2_const': np.array([args[71], args[72], args[73], args[74], args[75], args[76]]).reshape(-1, 2),
        'kst2_theta': np.array([args[77], args[78], args[79], args[80], args[81], args[82]]).reshape(-1, 2)
    }

def build_config(args, errors=None):
    def error(i):
        if errors is None:
            return 0.0
        return errors[i]

    def parameter(value, fixed, index=None, range_value=None):
        data = {'value': value}
        if range_value is not None:
            data['range'] = range_value
        data['fixed'] = fixed
        data['error'] = 0.0 if fixed else error(index)
        return data

    def a_propagator():
        return {
            'propagator_type': 'BW',
            'mass': parameter(1.02, True),
            'width': parameter(0.004, True),
            'Sbc': 'phi_kk'
        }

    return {
        'resonances': {
            'phif0_980': {
                'propagators': {
                    'A_propagator': a_propagator(),
                    'B_propagator': {
                        'propagator_type': 'flatte980',
                        'mass': parameter(args[0], False, 0, [0.98, 10.0]),
                        'g_kk': parameter(args[1], False, 1),
                        'rg': parameter(args[2], False, 2),
                        'Sbc': 'f_kk'
                    }
                },
                'Amplitude': {
                    'AMP': 'phif0_kk',
                    'const1': parameter(0.1, True),
                    'const2': parameter(args[3], False, 3),
                    'theta1': parameter(0.1, True),
                    'theta2': parameter(args[4], False, 4)
                }
            },
            'phif0_1710': {
                'propagators': {
                    'A_propagator': a_propagator(),
                    'B_propagator': {
                        'propagator_type': 'BW',
                        'mass': parameter(args[5], False, 5, [1.704, 1.0]),
                        'width': parameter(args[7], False, 7, [0.123, 1.0]),
                        'Sbc': 'f_kk'
                    }
                },
                'Amplitude': {
                    'AMP': 'phif0_kk',
                    'const1': parameter(args[9], False, 9),
                    'const2': parameter(args[10], False, 10),
                    'theta1': parameter(args[13], False, 13),
                    'theta2': parameter(args[14], False, 14)
                }
            },
            'phif2_1270': {
                'propagators': {
                    'A_propagator': a_propagator(),
                    'B_propagator': {
                        'propagator_type': 'flatte1270',
                        'mass': parameter(args[17], False, 17, [1.2755, 1.0]),
                        'width': parameter(args[18], False, 18, [0.1867, 1.0]),
                        'Sbc': 'f_kk'
                    }
                },
                'Amplitude': {
                    'AMP': 'phif2_kk',
                    'const1': parameter(args[19], False, 19),
                    'const2': parameter(args[20], False, 20),
                    'const3': parameter(args[21], False, 21),
                    'const4': parameter(args[22], False, 22),
                    'const5': parameter(args[23], False, 23),
                    'theta1': parameter(args[24], False, 24),
                    'theta2': parameter(args[25], False, 25),
                    'theta3': parameter(args[26], False, 26),
                    'theta4': parameter(args[27], False, 27),
                    'theta5': parameter(args[28], False, 28)
                }
            },
            'phif2_1525': {
                'propagators': {
                    'A_propagator': a_propagator(),
                    'B_propagator': {
                        'propagator_type': 'BW',
                        'mass': parameter(args[29], False, 29, [1.517, 1.0]),
                        'width': parameter(args[32], False, 32, [0.086, 1.0]),
                        'Sbc': 'f_kk'
                    }
                },
                'Amplitude': {
                    'AMP': 'phif2_kk',
                    'const1': parameter(args[35], False, 35),
                    'const2': parameter(args[36], False, 36),
                    'const3': parameter(args[37], False, 37),
                    'const4': parameter(args[38], False, 38),
                    'const5': parameter(args[39], False, 39),
                    'theta1': parameter(args[50], False, 50),
                    'theta2': parameter(args[51], False, 51),
                    'theta3': parameter(args[52], False, 52),
                    'theta4': parameter(args[53], False, 53),
                    'theta5': parameter(args[54], False, 54)
                }
            },
            'phif2_2150': {
                'propagators': {
                    'A_propagator': a_propagator(),
                    'B_propagator': {
                        'propagator_type': 'BW',
                        'mass': parameter(args[30], False, 30, [2.157, 1.0]),
                        'width': parameter(args[33], False, 33, [0.152, 1.0]),
                        'Sbc': 'f_kk'
                    }
                },
                'Amplitude': {
                    'AMP': 'phif2_kk',
                    'const1': parameter(args[40], False, 40),
                    'const2': parameter(args[41], False, 41),
                    'const3': parameter(args[42], False, 42),
                    'const4': parameter(args[43], False, 43),
                    'const5': parameter(args[44], False, 44),
                    'theta1': parameter(args[55], False, 55),
                    'theta2': parameter(args[56], False, 56),
                    'theta3': parameter(args[57], False, 57),
                    'theta4': parameter(args[58], False, 58),
                    'theta5': parameter(args[59], False, 59)
                }
            },
            'phif2_2340': {
                'propagators': {
                    'A_propagator': a_propagator(),
                    'B_propagator': {
                        'propagator_type': 'BW',
                        'mass': parameter(args[31], False, 31, [2.345, 0.01]),
                        'width': parameter(args[34], False, 34, [0.322, 1.0]),
                        'Sbc': 'f_kk'
                    }
                },
                'Amplitude': {
                    'AMP': 'phif2_kk',
                    'const1': parameter(args[45], False, 45),
                    'const2': parameter(args[46], False, 46),
                    'const3': parameter(args[47], False, 47),
                    'const4': parameter(args[48], False, 48),
                    'const5': parameter(args[49], False, 49),
                    'theta1': parameter(args[60], False, 60),
                    'theta2': parameter(args[61], False, 61),
                    'theta3': parameter(args[62], False, 62),
                    'theta4': parameter(args[63], False, 63),
                    'theta5': parameter(args[64], False, 64)
                }
            },
            'phif0_2470': {
                'propagators': {
                    'A_propagator': a_propagator(),
                    'B_propagator': {
                        'propagator_type': 'BW',
                        'mass': parameter(args[6], False, 6, [2.47, 0.007]),
                        'width': parameter(args[8], False, 8, [0.075, 0.011]),
                        'Sbc': 'f_kk'
                    }
                },
                'Amplitude': {
                    'AMP': 'phif0_kk',
                    'const1': parameter(args[11], False, 11),
                    'const2': parameter(args[12], False, 12),
                    'theta1': parameter(args[15], False, 15),
                    'theta2': parameter(args[16], False, 16)
                }
            },
            'K2100': {
                'kind': 'shared_state',
                'components': ['K2100_r', 'K2100_l'],
                'propagators': {
                    'A_propagator': a_propagator(),
                    'B_propagator': {
                        'propagator_type': 'BW',
                        'mass': parameter(args[65], False, 65, [2.1, 10.0]),
                        'width': parameter(args[68], False, 68, [0.1, 10.0])
                    }
                },
                'shared_amplitude_parameters': {
                    'const1': parameter(args[71], False, 71),
                    'const2': parameter(args[72], False, 72),
                    'theta1': parameter(args[77], False, 77),
                    'theta2': parameter(args[78], False, 78)
                },
                'amplitudes': [
                    {'name': 'K2100_r', 'AMP': 'u_kst2_r_kk', 'B_Sbc': 'kst2_124_kk', 'parameter_ref': 'shared_amplitude_parameters'},
                    {'name': 'K2100_l', 'AMP': 'u_kst2_l_kk', 'B_Sbc': 'kst2_123_kk', 'parameter_ref': 'shared_amplitude_parameters'}
                ]
            },
            'K1820': {
                'kind': 'shared_state',
                'components': ['K1820_r', 'K1820_l'],
                'propagators': {
                    'A_propagator': a_propagator(),
                    'B_propagator': {
                        'propagator_type': 'BW',
                        'mass': parameter(args[66], False, 66, [1.819, 10.0]),
                        'width': parameter(args[69], False, 69, [0.264, 10.0])
                    }
                },
                'shared_amplitude_parameters': {
                    'const1': parameter(args[73], False, 73),
                    'const2': parameter(args[74], False, 74),
                    'theta1': parameter(args[79], False, 79),
                    'theta2': parameter(args[80], False, 80)
                },
                'amplitudes': [
                    {'name': 'K1820_r', 'AMP': 'u_kst2_r_kk', 'B_Sbc': 'kst2_124_kk', 'parameter_ref': 'shared_amplitude_parameters'},
                    {'name': 'K1820_l', 'AMP': 'u_kst2_l_kk', 'B_Sbc': 'kst2_123_kk', 'parameter_ref': 'shared_amplitude_parameters'}
                ]
            },
            'K2250': {
                'kind': 'shared_state',
                'components': ['K2250_r', 'K2250_l'],
                'propagators': {
                    'A_propagator': a_propagator(),
                    'B_propagator': {
                        'propagator_type': 'BW',
                        'mass': parameter(args[67], False, 67, [2.247, 10.0]),
                        'width': parameter(args[70], False, 70, [0.18, 10.0])
                    }
                },
                'shared_amplitude_parameters': {
                    'const1': parameter(args[75], False, 75),
                    'const2': parameter(args[76], False, 76),
                    'theta1': parameter(args[81], False, 81),
                    'theta2': parameter(args[82], False, 82)
                },
                'amplitudes': [
                    {'name': 'K2250_r', 'AMP': 'u_kst2_r_kk', 'B_Sbc': 'kst2_124_kk', 'parameter_ref': 'shared_amplitude_parameters'},
                    {'name': 'K2250_l', 'AMP': 'u_kst2_l_kk', 'B_Sbc': 'kst2_123_kk', 'parameter_ref': 'shared_amplitude_parameters'}
                ]
            }
        },
        'draw': {
            'extra_sbc': ['b123_kk', 'b124_kk']
        }
    }

# === generated by LLM | cache: draw_weight_function_cache.json | hash: 848fc02d ===
def weight_kk(args):
    params = extract_parameters(args)
    comp_phif0_kk_BW_flatte980 = component_BW_flatte980(
        params['phi_mass'], params['phi_width'], data_phi_kk,
        params['f980_mass'], params['f980_g_kk'], params['f980_rg'], data_f_kk,
        data_phif0_kk, params['f980_const'], params['f980_theta']
    )
    comp_phif0_kk_BW_BW = component_BW_BW(
        params['phi_mass'], params['phi_width'], data_phi_kk,
        params['f0_mass'], params['f0_width'], data_f_kk,
        data_phif0_kk, params['f0_const'], params['f0_theta']
    )
    comp_phif2_kk_BW_flatte1270 = component_BW_flatte1270(
        params['phi_mass'], params['phi_width'], data_phi_kk,
        params['f1270_mass'], params['f1270_width'], data_f_kk,
        data_phif2_kk, params['f1270_const'], params['f1270_theta']
    )
    comp_phif2_kk_BW_BW = component_BW_BW(
        params['phi_mass'], params['phi_width'], data_phi_kk,
        params['f2_mass'], params['f2_width'], data_f_kk,
        data_phif2_kk, params['f2_const'], params['f2_theta']
    )
    comp_u_kst2_r_kk_BW_BW = component_BW_BW(
        params['phi_mass'], params['phi_width'], data_phi_kk,
        params['kst2_mass'], params['kst2_width'], data_kst2_124_kk,
        data_u_kst2_r_kk, params['kst2_const'], params['kst2_theta']
    )
    comp_u_kst2_l_kk_BW_BW = component_BW_BW(
        params['phi_mass'], params['phi_width'], data_phi_kk,
        params['kst2_mass'], params['kst2_width'], data_kst2_123_kk,
        data_u_kst2_l_kk, params['kst2_const'], params['kst2_theta']
    )
    total_wt = np.sum(dplex_dabs(
        np.einsum("mljk->mjk", comp_phif0_kk_BW_flatte980) +
        np.einsum("mljk->mjk", comp_phif0_kk_BW_BW) +
        np.einsum("mljk->mjk", comp_phif2_kk_BW_flatte1270) +
        np.einsum("mljk->mjk", comp_phif2_kk_BW_BW) +
        np.einsum("mljk->mjk", comp_u_kst2_r_kk_BW_BW) +
        np.einsum("mljk->mjk", comp_u_kst2_l_kk_BW_BW)
    ), axis=1)
    wt_list = [
        total_wt,
        np.einsum("ljk->lj", dplex_dabs(comp_phif0_kk_BW_flatte980)),
        np.einsum("ljk->lj", dplex_dabs(comp_phif0_kk_BW_BW)),
        np.einsum("ljk->lj", dplex_dabs(comp_phif2_kk_BW_flatte1270)),
        np.einsum("ljk->lj", dplex_dabs(comp_phif2_kk_BW_BW)),
        np.einsum("ljk->lj", dplex_dabs(comp_u_kst2_r_kk_BW_BW)),
        np.einsum("ljk->lj", dplex_dabs(comp_u_kst2_l_kk_BW_BW)),
    ]
    return wt_list

def weight_truth_kk(args):
    params = extract_parameters(args)
    comp_phif0_kk_BW_flatte980 = component_BW_flatte980(
        params['phi_mass'], params['phi_width'], truth_phi_kk,
        params['f980_mass'], params['f980_g_kk'], params['f980_rg'], truth_f_kk,
        truth_phif0_kk, params['f980_const'], params['f980_theta']
    )
    comp_phif0_kk_BW_BW = component_BW_BW(
        params['phi_mass'], params['phi_width'], truth_phi_kk,
        params['f0_mass'], params['f0_width'], truth_f_kk,
        truth_phif0_kk, params['f0_const'], params['f0_theta']
    )
    comp_phif2_kk_BW_flatte1270 = component_BW_flatte1270(
        params['phi_mass'], params['phi_width'], truth_phi_kk,
        params['f1270_mass'], params['f1270_width'], truth_f_kk,
        truth_phif2_kk, params['f1270_const'], params['f1270_theta']
    )
    comp_phif2_kk_BW_BW = component_BW_BW(
        params['phi_mass'], params['phi_width'], truth_phi_kk,
        params['f2_mass'], params['f2_width'], truth_f_kk,
        truth_phif2_kk, params['f2_const'], params['f2_theta']
    )
    comp_u_kst2_r_kk_BW_BW = component_BW_BW(
        params['phi_mass'], params['phi_width'], truth_phi_kk,
        params['kst2_mass'], params['kst2_width'], truth_kst2_124_kk,
        truth_u_kst2_r_kk, params['kst2_const'], params['kst2_theta']
    )
    comp_u_kst2_l_kk_BW_BW = component_BW_BW(
        params['phi_mass'], params['phi_width'], truth_phi_kk,
        params['kst2_mass'], params['kst2_width'], truth_kst2_123_kk,
        truth_u_kst2_l_kk, params['kst2_const'], params['kst2_theta']
    )
    total_wt = np.sum(dplex_dabs(
        np.einsum("mljk->mjk", comp_phif0_kk_BW_flatte980) +
        np.einsum("mljk->mjk", comp_phif0_kk_BW_BW) +
        np.einsum("mljk->mjk", comp_phif2_kk_BW_flatte1270) +
        np.einsum("mljk->mjk", comp_phif2_kk_BW_BW) +
        np.einsum("mljk->mjk", comp_u_kst2_r_kk_BW_BW) +
        np.einsum("mljk->mjk", comp_u_kst2_l_kk_BW_BW)
    ), axis=1)
    wt_list = [
        total_wt,
        np.einsum("ljk->lj", dplex_dabs(comp_phif0_kk_BW_flatte980)),
        np.einsum("ljk->lj", dplex_dabs(comp_phif0_kk_BW_BW)),
        np.einsum("ljk->lj", dplex_dabs(comp_phif2_kk_BW_flatte1270)),
        np.einsum("ljk->lj", dplex_dabs(comp_phif2_kk_BW_BW)),
        np.einsum("ljk->lj", dplex_dabs(comp_u_kst2_r_kk_BW_BW)),
        np.einsum("ljk->lj", dplex_dabs(comp_u_kst2_l_kk_BW_BW)),
    ]
    return wt_list

def run_weight(args_list, mode="pass"):
    args = np.array(args_list)
    jit_weight = jit(weight_kk)
    jit_weight_truth = jit(weight_truth_kk)
    if mode == "pass":
        wt_list = jit_weight(args)
    elif mode == "truth":
        wt_list = jit_weight_truth(args)
    sum_wt = onp.sum(wt_list[0])
    total_weight = {"all_mods_wt": wt_list[0]}
    total_fit_frac = 0.0
    resonance_names = [
        "phif0_kk_BW_flatte980",
        "phif0_kk_BW_BW",
        "phif2_kk_BW_flatte1270",
        "phif2_kk_BW_BW",
        "u_kst2_r_kk_BW_BW",
        "u_kst2_l_kk_BW_BW"
    ]
    for i, name in enumerate(resonance_names):
        wt = wt_list[i + 1]
        for j in range(wt.shape[0]):
            key = f"{name}_{j}"
            total_weight[key] = wt[j]
            frac = onp.sum(wt[j]) / sum_wt
            print(f"{key} frac: {frac}")
            total_fit_frac += frac
    total_weight["fit_value"] = onp.array(args_list)
    total_weight["sum_wt"] = sum_wt
    print(f"total fit fraction: {total_fit_frac}")
    os.makedirs("output/draw", exist_ok=True)
    if mode == "pass":
        onp.savez("output/draw/weight.npz", **total_weight)
    elif mode == "truth":
        onp.savez("output/draw/weight_truth.npz", **total_weight)
    return total_fit_frac

# === generated by LLM | cache: draw_run_load_data_cache.json | hash: acf208bc ===
data = load_data()
data = normalize_data(data)
jax_data = prepare_data_for_jax(data)

# 实验数据
data_phi_kk = jax_data['data_phi_kk']
data_f_kk = jax_data['data_f_kk']
data_kst2_124_kk = jax_data['data_kst2_124_kk']
data_kst2_123_kk = jax_data['data_kst2_123_kk']
data_phif0_kk = jax_data['data_phif0_kk']
data_phif2_kk = jax_data['data_phif2_kk']
data_u_kst2_r_kk = jax_data['data_u_kst2_r_kk']
data_u_kst2_l_kk = jax_data['data_u_kst2_l_kk']
data_b123_kk = jax_data['data_b123_kk']
data_b124_kk = jax_data['data_b124_kk']

# MC数据
mc_phi_kk = jax_data['mc_phi_kk']
mc_f_kk = jax_data['mc_f_kk']
mc_kst2_124_kk = jax_data['mc_kst2_124_kk']
mc_kst2_123_kk = jax_data['mc_kst2_123_kk']
mc_phif0_kk = jax_data['mc_phif0_kk']
mc_phif2_kk = jax_data['mc_phif2_kk']
mc_u_kst2_r_kk = jax_data['mc_u_kst2_r_kk']
mc_u_kst2_l_kk = jax_data['mc_u_kst2_l_kk']
mc_b123_kk = jax_data['mc_b123_kk']
mc_b124_kk = jax_data['mc_b124_kk']

# Truth数据
truth_phi_kk = jax_data['truth_phi_kk']
truth_f_kk = jax_data['truth_f_kk']
truth_kst2_124_kk = jax_data['truth_kst2_124_kk']
truth_kst2_123_kk = jax_data['truth_kst2_123_kk']
truth_phif0_kk = jax_data['truth_phif0_kk']
truth_phif2_kk = jax_data['truth_phif2_kk']
truth_u_kst2_r_kk = jax_data['truth_u_kst2_r_kk']
truth_u_kst2_l_kk = jax_data['truth_u_kst2_l_kk']
truth_b123_kk = jax_data['truth_b123_kk']
truth_b124_kk = jax_data['truth_b124_kk']

# === generated by LLM | cache: draw_main_section_cache.json | hash: 926a79f8 ===
if __name__ == "__main__":
    logger = setup_logging()
    config.update("jax_enable_x64", True)

    args_list = onp.load("output/fit/fit_result_values.npy")

    logger.info("计算数据权重 (mode=pass)...")
    run_weight(args_list, mode="pass")

    logger.info("计算 truth MC 权重 (mode=truth)...")
    run_weight(args_list, mode="truth")

    logger.info("权重计算完成，结果已保存至 output/draw/")