# Auto-generated by LLMResonanceGenerator — do not edit manually
import copy
import json
import logging
import logging.config
import os
# must set before importing jax
os.environ["XLA_PYTHON_CLIENT_PREALLOCATE"] = "false"
import time
import numpy as onp
from functools import partial
from scipy.optimize import minimize

import jax.numpy as np
from jax import device_put, grad, jit, vmap, jvp
from jax import config



import sys
foo_path = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(foo_path)
sys.path.append(foo_path)



def setup_logging():
    """Setup logging configuration"""
    with open("config/logconfig_fit.json", "r") as config_file:
        LOGGING_CONFIG = json.load(config_file)
        logging.config.dictConfig(LOGGING_CONFIG)
    return logging.getLogger("fit")



def dplex_deinsum(subscript, aa, bb):
    real = np.einsum(subscript, aa[0], bb[0]) - np.einsum(subscript, aa[1], bb[1])
    imag = np.einsum(subscript, aa[0], bb[1]) + np.einsum(subscript, aa[1], bb[0])
    return np.stack([real, imag], axis=0)

def dplex_deinsum_ord(subscript, aa, bb):
    real = np.einsum(subscript, aa, bb[0])
    imag = np.einsum(subscript, aa, bb[1])
    return np.stack([real, imag], axis=0)

def dplex_dabs(aa):
    return aa[0]**2 + aa[1]**2 # 因为是纵向叠加所以aa[0]是纵向上第一个数组

def dplex_dtomine(aa):
    return np.stack([np.real(aa), np.imag(aa)], axis=0) # 组合而成的数组 axis=0 的第一个数组为实部，第二个数组为虚部

def dplex_dconstruct(aa, bb):
    return np.stack([aa, bb], axis=0) # 纵向叠加数组 第一维为实部，第二维为虚部

def dplex_ddivide(a, bb):
    real = a * bb[0] / dplex_dabs(bb)
    imag = -a * bb[1] / dplex_dabs(bb)
    return np.stack([real, imag], axis=0)


#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# ==============================================================================
# SECTION: PHYSICS_FUNCTIONS
# Physics calculation functions (resonance shape functions)
# Provided by the user for each analysis. Copy this file to your analysis
# directory as physics_functions.py and keep only the functions you need.
# ==============================================================================

import jax.numpy as np


def BW(m_, w_, Sbc):
    l = (Sbc.shape)[0]
    temp = dplex_dconstruct(m_*m_ - Sbc, -m_*w_*np.ones(l))
    return dplex_ddivide(1.0, temp)


def BW_relativity(m_, w_, Sbc):
    gamma = np.sqrt(m_*m_*(m_*m_+w_*w_))
    k = np.sqrt(2*np.sqrt(2)*m_*np.abs(w_)*gamma/np.pi/np.sqrt(m_*m_+gamma))
    l = (Sbc.shape)[0]
    temp = dplex_dconstruct(m_*m_ - Sbc, -m_*w_*np.ones(l))
    return dplex_ddivide(k, temp)


def flatte980(m_, g_pipi, rg, Sbc):
    g_kk = rg * g_pipi
    m_k = 0.493677
    m_pi = 0.13957061
    rho_kk = np.sqrt(np.abs(1 - 4*m_k*m_k / Sbc))
    rho_pipi = np.sqrt(np.abs(1 - 4*m_pi*m_pi / Sbc))
    tmp_A = dplex_dconstruct(m_**2 - Sbc, -1*(g_pipi*rho_pipi + g_kk*rho_kk))
    return dplex_ddivide(1.0, tmp_A)


def flatte1270(m_, w_, Sbc):
    rm = m_ * m_
    gr = m_ * w_
    q2r = 0.25 * rm - 0.0194792
    b2r = q2r * (q2r + 0.1825) + 0.033306
    g11270 = gr * b2r / np.power(q2r, 2.5)
    q2 = 0.25 * Sbc - 0.0194792
    b2 = q2 * (q2 + 0.1825) + 0.033306
    g1 = g11270 * np.power(q2, 2.5) / b2
    tmp = dplex_dconstruct(Sbc - rm, g1)
    return dplex_ddivide(gr, tmp)


def flatte500(m_, b1, b2, b3, b4, b5, Sbc):
    m2 = m_*m_
    rp = 0.139556995
    mpi2d2 = 0.009739946882
    cro1 = np.sqrt(np.abs((Sbc-(2*rp)**2)*Sbc))/Sbc
    cro2 = np.sqrt(np.abs((m2-(2*rp)**2)*m2))/m2
    pip1 = np.sqrt(np.abs(1.0 - 0.3116765584/Sbc))/(1.0+np.exp(9.8-3.5*Sbc))
    pip2 = np.sqrt(np.abs(1.0 - 0.3116765584/m2))/(1.0+np.exp(9.8-3.5*m2))
    cgam1 = m_*(b1+b2*Sbc)*(Sbc-mpi2d2)/(m2-mpi2d2)*np.exp(-(Sbc-m2)/b3)*cro1/cro2
    cgam2 = m_*b4*pip1/pip2
    tmp = dplex_dconstruct(m2-Sbc, -b5*(cgam1+cgam2))
    return dplex_ddivide(1.0, tmp)


def load_data():
    data = {}

    # Load real data
    data['data_phi_kk'] = onp.load("data/real_data/phi_kk.npy")
    data['data_f_kk'] = onp.load("data/real_data/f_kk.npy")
    data['data_kst2_124_kk'] = onp.load("data/real_data/kst2_124_kk.npy")
    data['data_kst2_123_kk'] = onp.load("data/real_data/kst2_123_kk.npy")
    data['data_phif0_kk'] = onp.load("data/real_data/phif0_kk.npy")
    data['data_phif2_kk'] = onp.load("data/real_data/phif2_kk.npy")
    data['data_u_kst2_r_kk'] = onp.load("data/real_data/u_kst2_r_kk.npy")
    data['data_u_kst2_l_kk'] = onp.load("data/real_data/u_kst2_l_kk.npy")

    # Load MC data
    data['mc_phi_kk'] = onp.load("data/mc_truth/phi_kk.npy")
    data['mc_f_kk'] = onp.load("data/mc_truth/f_kk.npy")
    data['mc_kst2_124_kk'] = onp.load("data/mc_truth/kst2_124_kk.npy")
    data['mc_kst2_123_kk'] = onp.load("data/mc_truth/kst2_123_kk.npy")
    data['mc_phif0_kk'] = onp.load("data/mc_truth/phif0_kk.npy")
    data['mc_phif2_kk'] = onp.load("data/mc_truth/phif2_kk.npy")
    data['mc_u_kst2_r_kk'] = onp.load("data/mc_truth/u_kst2_r_kk.npy")
    data['mc_u_kst2_l_kk'] = onp.load("data/mc_truth/u_kst2_l_kk.npy")

    # MC truth data (for constraints)
    data['truth_phi_kk'] = data['mc_phi_kk'][0:150000]
    data['truth_f_kk'] = data['mc_f_kk'][0:150000]
    data['truth_kst2_124_kk'] = data['mc_kst2_124_kk'][0:150000]
    data['truth_kst2_123_kk'] = data['mc_kst2_123_kk'][0:150000]
    data['truth_phif0_kk'] = data['mc_phif0_kk'][:, 0:150000]
    data['truth_phif2_kk'] = data['mc_phif2_kk'][:, 0:150000]
    data['truth_u_kst2_r_kk'] = data['mc_u_kst2_r_kk'][:, 0:150000]
    data['truth_u_kst2_l_kk'] = data['mc_u_kst2_l_kk'][:, 0:150000]

    # Weight data
    try:
        data['wt_data_kk'] = onp.load("data/weight/weight_kk.npy")
    except FileNotFoundError:
        data['wt_data_kk'] = onp.ones_like(data['data_phi_kk'])

    return data

def normalize_data(data):
    # 计算归一化因子
    regular_phif0_kk = 1. / onp.average(
        onp.sqrt(onp.sum(onp.asarray(data['mc_phif0_kk'])**2, axis=2)), axis=1
    )
    regular_phif2_kk = 1. / onp.average(
        onp.sqrt(onp.sum(onp.asarray(data['mc_phif2_kk'])**2, axis=2)), axis=1
    )
    regular_u_kst2_r_kk = 1. / onp.average(
        onp.sqrt(onp.sum(onp.asarray(data['mc_u_kst2_r_kk'])**2, axis=2)), axis=1
    )
    regular_u_kst2_l_kk = 1. / onp.average(
        onp.sqrt(onp.sum(onp.asarray(data['mc_u_kst2_l_kk'])**2, axis=2)), axis=1
    )

    # 应用归一化
    data['data_phif0_kk'] = onp.einsum("jkl,j->jkl", data['data_phif0_kk'], regular_phif0_kk)
    data['mc_phif0_kk'] = onp.einsum("jkl,j->jkl", data['mc_phif0_kk'], regular_phif0_kk)
    data['truth_phif0_kk'] = onp.einsum("jkl,j->jkl", data['truth_phif0_kk'], regular_phif0_kk)
    data['data_phif2_kk'] = onp.einsum("jkl,j->jkl", data['data_phif2_kk'], regular_phif2_kk)
    data['mc_phif2_kk'] = onp.einsum("jkl,j->jkl", data['mc_phif2_kk'], regular_phif2_kk)
    data['truth_phif2_kk'] = onp.einsum("jkl,j->jkl", data['truth_phif2_kk'], regular_phif2_kk)
    data['data_u_kst2_r_kk'] = onp.einsum("jkl,j->jkl", data['data_u_kst2_r_kk'], regular_u_kst2_r_kk)
    data['mc_u_kst2_r_kk'] = onp.einsum("jkl,j->jkl", data['mc_u_kst2_r_kk'], regular_u_kst2_r_kk)
    data['truth_u_kst2_r_kk'] = onp.einsum("jkl,j->jkl", data['truth_u_kst2_r_kk'], regular_u_kst2_r_kk)
    data['data_u_kst2_l_kk'] = onp.einsum("jkl,j->jkl", data['data_u_kst2_l_kk'], regular_u_kst2_l_kk)
    data['mc_u_kst2_l_kk'] = onp.einsum("jkl,j->jkl", data['mc_u_kst2_l_kk'], regular_u_kst2_l_kk)
    data['truth_u_kst2_l_kk'] = onp.einsum("jkl,j->jkl", data['truth_u_kst2_l_kk'], regular_u_kst2_l_kk)

    return data

def prepare_data_for_jax(data, device=None):
    jax_data = {}
    for key, value in data.items():
        jax_data[key] = device_put(np.array(value), device=device)
    return jax_data

def calculate_BW_BW(A_mass, A_width, phi_kk, B_mass, B_width, f_kk, Amplitude_param_AMP, Amplitude_param_const, Amplitude_param_theta):
    A_propagator = BW(A_mass, A_width, phi_kk)
    B_propagator = np.moveaxis(
        vmap(partial(BW, Sbc=f_kk))(B_mass, B_width), 1, 0
    )
    propagator_combined = dplex_deinsum("j, ij->ij", A_propagator, B_propagator)
    const_ph = dplex_dconstruct(Amplitude_param_const, Amplitude_param_theta)
    result = dplex_deinsum_ord("ijk,li->ljk", Amplitude_param_AMP, const_ph)
    result = dplex_deinsum("ljk,lj->jk", result, propagator_combined)
    return result

def component_BW_BW(A_mass, A_width, phi_kk, B_mass, B_width, f_kk, Amplitude_param_AMP, Amplitude_param_const, Amplitude_param_theta):
    A_propagator = BW(A_mass, A_width, phi_kk)
    B_propagator = np.moveaxis(
        vmap(partial(BW, Sbc=f_kk))(B_mass, B_width), 1, 0
    )
    propagator_combined = dplex_deinsum("j, ij->ij", A_propagator, B_propagator)
    const_ph = dplex_dconstruct(Amplitude_param_const, Amplitude_param_theta)
    result = dplex_deinsum_ord("ijk,li->ljk", Amplitude_param_AMP, const_ph)
    result = dplex_deinsum("ljk,lj->ljk", result, propagator_combined)
    return result

def calculate_BW_flatte980(A_mass, A_width, phi_kk, B_mass, B_g_kk, B_rg, f_kk, Amplitude_param_AMP, Amplitude_param_const, Amplitude_param_theta):
    A_propagator = BW(A_mass, A_width, phi_kk)
    B_propagator = flatte980(B_mass, B_g_kk, B_rg, f_kk)
    propagator_combined = dplex_deinsum("j, j->j", A_propagator, B_propagator)
    const_ph = dplex_dconstruct(Amplitude_param_const, Amplitude_param_theta)
    result = dplex_deinsum_ord("ijk,li->ljk", Amplitude_param_AMP, const_ph)
    result = dplex_deinsum("ljk,j->jk", result, propagator_combined)
    return result

def component_BW_flatte980(A_mass, A_width, phi_kk, B_mass, B_g_kk, B_rg, f_kk, Amplitude_param_AMP, Amplitude_param_const, Amplitude_param_theta):
    A_propagator = BW(A_mass, A_width, phi_kk)
    B_propagator = flatte980(B_mass, B_g_kk, B_rg, f_kk)
    propagator_combined = dplex_deinsum("j, j->j", A_propagator, B_propagator)
    const_ph = dplex_dconstruct(Amplitude_param_const, Amplitude_param_theta)
    result = dplex_deinsum_ord("ijk,li->ljk", Amplitude_param_AMP, const_ph)
    result = dplex_deinsum("ljk,j->ljk", result, propagator_combined)
    return result

def calculate_BW_flatte1270(A_mass, A_width, phi_kk, B_mass, B_width, f_kk, Amplitude_param_AMP, Amplitude_param_const, Amplitude_param_theta):
    A_propagator = BW(A_mass, A_width, phi_kk)
    B_propagator = flatte1270(B_mass, B_width, f_kk)
    propagator_combined = dplex_deinsum("j, j->j", A_propagator, B_propagator)
    const_ph = dplex_dconstruct(Amplitude_param_const, Amplitude_param_theta)
    result = dplex_deinsum_ord("ijk,li->ljk", Amplitude_param_AMP, const_ph)
    result = dplex_deinsum("ljk,j->jk", result, propagator_combined)
    return result

def component_BW_flatte1270(A_mass, A_width, phi_kk, B_mass, B_width, f_kk, Amplitude_param_AMP, Amplitude_param_const, Amplitude_param_theta):
    A_propagator = BW(A_mass, A_width, phi_kk)
    B_propagator = flatte1270(B_mass, B_width, f_kk)
    propagator_combined = dplex_deinsum("j, j->j", A_propagator, B_propagator)
    const_ph = dplex_dconstruct(Amplitude_param_const, Amplitude_param_theta)
    result = dplex_deinsum_ord("ijk,li->ljk", Amplitude_param_AMP, const_ph)
    result = dplex_deinsum("ljk,j->ljk", result, propagator_combined)
    return result

def extract_parameters(args):
    phif0_980_B_propagator_mass = args[0]  # resonances.phif0_980.propagators.B_propagator.mass
    phif0_980_B_propagator_g_kk = args[1]  # resonances.phif0_980.propagators.B_propagator.g_kk
    phif0_980_B_propagator_rg = args[2]  # resonances.phif0_980.propagators.B_propagator.rg
    phif0_980_const2 = args[3]  # resonances.phif0_980.Amplitude.const2
    phif0_980_theta2 = args[4]  # resonances.phif0_980.Amplitude.theta2
    phif0_1710_B_propagator_mass = args[5]  # resonances.phif0_1710.propagators.B_propagator.mass
    phif0_1710_B_propagator_width = args[6]  # resonances.phif0_1710.propagators.B_propagator.width
    phif0_1710_const1 = args[7]  # resonances.phif0_1710.Amplitude.const1
    phif0_1710_const2 = args[8]  # resonances.phif0_1710.Amplitude.const2
    phif0_1710_theta1 = args[9]  # resonances.phif0_1710.Amplitude.theta1
    phif0_1710_theta2 = args[10]  # resonances.phif0_1710.Amplitude.theta2
    phif2_1270_B_propagator_mass = args[11]  # resonances.phif2_1270.propagators.B_propagator.mass
    phif2_1270_B_propagator_width = args[12]  # resonances.phif2_1270.propagators.B_propagator.width
    phif2_1270_const1 = args[13]  # resonances.phif2_1270.Amplitude.const1
    phif2_1270_const2 = args[14]  # resonances.phif2_1270.Amplitude.const2
    phif2_1270_const3 = args[15]  # resonances.phif2_1270.Amplitude.const3
    phif2_1270_const4 = args[16]  # resonances.phif2_1270.Amplitude.const4
    phif2_1270_const5 = args[17]  # resonances.phif2_1270.Amplitude.const5
    phif2_1270_theta1 = args[18]  # resonances.phif2_1270.Amplitude.theta1
    phif2_1270_theta2 = args[19]  # resonances.phif2_1270.Amplitude.theta2
    phif2_1270_theta3 = args[20]  # resonances.phif2_1270.Amplitude.theta3
    phif2_1270_theta4 = args[21]  # resonances.phif2_1270.Amplitude.theta4
    phif2_1270_theta5 = args[22]  # resonances.phif2_1270.Amplitude.theta5
    phif2_1525_B_propagator_mass = args[23]  # resonances.phif2_1525.propagators.B_propagator.mass
    phif2_1525_B_propagator_width = args[24]  # resonances.phif2_1525.propagators.B_propagator.width
    phif2_1525_const1 = args[25]  # resonances.phif2_1525.Amplitude.const1
    phif2_1525_const2 = args[26]  # resonances.phif2_1525.Amplitude.const2
    phif2_1525_const3 = args[27]  # resonances.phif2_1525.Amplitude.const3
    phif2_1525_const4 = args[28]  # resonances.phif2_1525.Amplitude.const4
    phif2_1525_const5 = args[29]  # resonances.phif2_1525.Amplitude.const5
    phif2_1525_theta1 = args[30]  # resonances.phif2_1525.Amplitude.theta1
    phif2_1525_theta2 = args[31]  # resonances.phif2_1525.Amplitude.theta2
    phif2_1525_theta3 = args[32]  # resonances.phif2_1525.Amplitude.theta3
    phif2_1525_theta4 = args[33]  # resonances.phif2_1525.Amplitude.theta4
    phif2_1525_theta5 = args[34]  # resonances.phif2_1525.Amplitude.theta5
    phif2_2150_B_propagator_mass = args[35]  # resonances.phif2_2150.propagators.B_propagator.mass
    phif2_2150_B_propagator_width = args[36]  # resonances.phif2_2150.propagators.B_propagator.width
    phif2_2150_const1 = args[37]  # resonances.phif2_2150.Amplitude.const1
    phif2_2150_const2 = args[38]  # resonances.phif2_2150.Amplitude.const2
    phif2_2150_const3 = args[39]  # resonances.phif2_2150.Amplitude.const3
    phif2_2150_const4 = args[40]  # resonances.phif2_2150.Amplitude.const4
    phif2_2150_const5 = args[41]  # resonances.phif2_2150.Amplitude.const5
    phif2_2150_theta1 = args[42]  # resonances.phif2_2150.Amplitude.theta1
    phif2_2150_theta2 = args[43]  # resonances.phif2_2150.Amplitude.theta2
    phif2_2150_theta3 = args[44]  # resonances.phif2_2150.Amplitude.theta3
    phif2_2150_theta4 = args[45]  # resonances.phif2_2150.Amplitude.theta4
    phif2_2150_theta5 = args[46]  # resonances.phif2_2150.Amplitude.theta5
    phif2_2340_B_propagator_mass = args[47]  # resonances.phif2_2340.propagators.B_propagator.mass
    phif2_2340_B_propagator_width = args[48]  # resonances.phif2_2340.propagators.B_propagator.width
    phif2_2340_const1 = args[49]  # resonances.phif2_2340.Amplitude.const1
    phif2_2340_const2 = args[50]  # resonances.phif2_2340.Amplitude.const2
    phif2_2340_const3 = args[51]  # resonances.phif2_2340.Amplitude.const3
    phif2_2340_const4 = args[52]  # resonances.phif2_2340.Amplitude.const4
    phif2_2340_const5 = args[53]  # resonances.phif2_2340.Amplitude.const5
    phif2_2340_theta1 = args[54]  # resonances.phif2_2340.Amplitude.theta1
    phif2_2340_theta2 = args[55]  # resonances.phif2_2340.Amplitude.theta2
    phif2_2340_theta3 = args[56]  # resonances.phif2_2340.Amplitude.theta3
    phif2_2340_theta4 = args[57]  # resonances.phif2_2340.Amplitude.theta4
    phif2_2340_theta5 = args[58]  # resonances.phif2_2340.Amplitude.theta5
    phif0_2470_B_propagator_mass = args[59]  # resonances.phif0_2470.propagators.B_propagator.mass
    phif0_2470_B_propagator_width = args[60]  # resonances.phif0_2470.propagators.B_propagator.width
    phif0_2470_const1 = args[61]  # resonances.phif0_2470.Amplitude.const1
    phif0_2470_const2 = args[62]  # resonances.phif0_2470.Amplitude.const2
    phif0_2470_theta1 = args[63]  # resonances.phif0_2470.Amplitude.theta1
    phif0_2470_theta2 = args[64]  # resonances.phif0_2470.Amplitude.theta2
    K2100_B_propagator_mass = args[65]  # resonances.K2100.propagators.B_propagator.mass
    K2100_B_propagator_width = args[66]  # resonances.K2100.propagators.B_propagator.width
    K2100_const1 = args[67]  # resonances.K2100.shared_amplitude_parameters.const1
    K2100_const2 = args[68]  # resonances.K2100.shared_amplitude_parameters.const2
    K2100_theta1 = args[69]  # resonances.K2100.shared_amplitude_parameters.theta1
    K2100_theta2 = args[70]  # resonances.K2100.shared_amplitude_parameters.theta2
    K1820_B_propagator_mass = args[71]  # resonances.K1820.propagators.B_propagator.mass
    K1820_B_propagator_width = args[72]  # resonances.K1820.propagators.B_propagator.width
    K1820_const1 = args[73]  # resonances.K1820.shared_amplitude_parameters.const1
    K1820_const2 = args[74]  # resonances.K1820.shared_amplitude_parameters.const2
    K1820_theta1 = args[75]  # resonances.K1820.shared_amplitude_parameters.theta1
    K1820_theta2 = args[76]  # resonances.K1820.shared_amplitude_parameters.theta2
    K2250_B_propagator_mass = args[77]  # resonances.K2250.propagators.B_propagator.mass
    K2250_B_propagator_width = args[78]  # resonances.K2250.propagators.B_propagator.width
    K2250_const1 = args[79]  # resonances.K2250.shared_amplitude_parameters.const1
    K2250_const2 = args[80]  # resonances.K2250.shared_amplitude_parameters.const2
    K2250_theta1 = args[81]  # resonances.K2250.shared_amplitude_parameters.theta1
    K2250_theta2 = args[82]  # resonances.K2250.shared_amplitude_parameters.theta2
    return phif0_980_B_propagator_mass, phif0_980_B_propagator_g_kk, phif0_980_B_propagator_rg, phif0_980_const2, phif0_980_theta2, phif0_1710_B_propagator_mass, phif0_1710_B_propagator_width, phif0_1710_const1, phif0_1710_const2, phif0_1710_theta1, phif0_1710_theta2, phif2_1270_B_propagator_mass, phif2_1270_B_propagator_width, phif2_1270_const1, phif2_1270_const2, phif2_1270_const3, phif2_1270_const4, phif2_1270_const5, phif2_1270_theta1, phif2_1270_theta2, phif2_1270_theta3, phif2_1270_theta4, phif2_1270_theta5, phif2_1525_B_propagator_mass, phif2_1525_B_propagator_width, phif2_1525_const1, phif2_1525_const2, phif2_1525_const3, phif2_1525_const4, phif2_1525_const5, phif2_1525_theta1, phif2_1525_theta2, phif2_1525_theta3, phif2_1525_theta4, phif2_1525_theta5, phif2_2150_B_propagator_mass, phif2_2150_B_propagator_width, phif2_2150_const1, phif2_2150_const2, phif2_2150_const3, phif2_2150_const4, phif2_2150_const5, phif2_2150_theta1, phif2_2150_theta2, phif2_2150_theta3, phif2_2150_theta4, phif2_2150_theta5, phif2_2340_B_propagator_mass, phif2_2340_B_propagator_width, phif2_2340_const1, phif2_2340_const2, phif2_2340_const3, phif2_2340_const4, phif2_2340_const5, phif2_2340_theta1, phif2_2340_theta2, phif2_2340_theta3, phif2_2340_theta4, phif2_2340_theta5, phif0_2470_B_propagator_mass, phif0_2470_B_propagator_width, phif0_2470_const1, phif0_2470_const2, phif0_2470_theta1, phif0_2470_theta2, K2100_B_propagator_mass, K2100_B_propagator_width, K2100_const1, K2100_const2, K2100_theta1, K2100_theta2, K1820_B_propagator_mass, K1820_B_propagator_width, K1820_const1, K1820_const2, K1820_theta1, K1820_theta2, K2250_B_propagator_mass, K2250_B_propagator_width, K2250_const1, K2250_const2, K2250_theta1, K2250_theta2

def data_likelihood_kk(args):
    params = extract_parameters(args)
    phif0_980_B_propagator_mass, phif0_980_B_propagator_g_kk, phif0_980_B_propagator_rg, phif0_980_const2, phif0_980_theta2, phif0_1710_B_propagator_mass, phif0_1710_B_propagator_width, phif0_1710_const1, phif0_1710_const2, phif0_1710_theta1, phif0_1710_theta2, phif2_1270_B_propagator_mass, phif2_1270_B_propagator_width, phif2_1270_const1, phif2_1270_const2, phif2_1270_const3, phif2_1270_const4, phif2_1270_const5, phif2_1270_theta1, phif2_1270_theta2, phif2_1270_theta3, phif2_1270_theta4, phif2_1270_theta5, phif2_1525_B_propagator_mass, phif2_1525_B_propagator_width, phif2_1525_const1, phif2_1525_const2, phif2_1525_const3, phif2_1525_const4, phif2_1525_const5, phif2_1525_theta1, phif2_1525_theta2, phif2_1525_theta3, phif2_1525_theta4, phif2_1525_theta5, phif2_2150_B_propagator_mass, phif2_2150_B_propagator_width, phif2_2150_const1, phif2_2150_const2, phif2_2150_const3, phif2_2150_const4, phif2_2150_const5, phif2_2150_theta1, phif2_2150_theta2, phif2_2150_theta3, phif2_2150_theta4, phif2_2150_theta5, phif2_2340_B_propagator_mass, phif2_2340_B_propagator_width, phif2_2340_const1, phif2_2340_const2, phif2_2340_const3, phif2_2340_const4, phif2_2340_const5, phif2_2340_theta1, phif2_2340_theta2, phif2_2340_theta3, phif2_2340_theta4, phif2_2340_theta5, phif0_2470_B_propagator_mass, phif0_2470_B_propagator_width, phif0_2470_const1, phif0_2470_const2, phif0_2470_theta1, phif0_2470_theta2, K2100_B_propagator_mass, K2100_B_propagator_width, K2100_const1, K2100_const2, K2100_theta1, K2100_theta2, K1820_B_propagator_mass, K1820_B_propagator_width, K1820_const1, K1820_const2, K1820_theta1, K1820_theta2, K2250_B_propagator_mass, K2250_B_propagator_width, K2250_const1, K2250_const2, K2250_theta1, K2250_theta2 = params
    phif0_980_const = np.array([1.0, phif0_980_const2])
    phif0_980_theta = np.array([0.0, phif0_980_theta2])
    phif0_1710_const = np.array([phif0_1710_const1, phif0_1710_const2])
    phif0_1710_theta = np.array([phif0_1710_theta1, phif0_1710_theta2])
    phif2_1270_const = np.array([phif2_1270_const1, phif2_1270_const2, phif2_1270_const3, phif2_1270_const4, phif2_1270_const5])
    phif2_1270_theta = np.array([phif2_1270_theta1, phif2_1270_theta2, phif2_1270_theta3, phif2_1270_theta4, phif2_1270_theta5])
    phif2_1525_const = np.array([phif2_1525_const1, phif2_1525_const2, phif2_1525_const3, phif2_1525_const4, phif2_1525_const5])
    phif2_1525_theta = np.array([phif2_1525_theta1, phif2_1525_theta2, phif2_1525_theta3, phif2_1525_theta4, phif2_1525_theta5])
    phif2_2150_const = np.array([phif2_2150_const1, phif2_2150_const2, phif2_2150_const3, phif2_2150_const4, phif2_2150_const5])
    phif2_2150_theta = np.array([phif2_2150_theta1, phif2_2150_theta2, phif2_2150_theta3, phif2_2150_theta4, phif2_2150_theta5])
    phif2_2340_const = np.array([phif2_2340_const1, phif2_2340_const2, phif2_2340_const3, phif2_2340_const4, phif2_2340_const5])
    phif2_2340_theta = np.array([phif2_2340_theta1, phif2_2340_theta2, phif2_2340_theta3, phif2_2340_theta4, phif2_2340_theta5])
    phif0_2470_const = np.array([phif0_2470_const1, phif0_2470_const2])
    phif0_2470_theta = np.array([phif0_2470_theta1, phif0_2470_theta2])
    K2100_const = np.array([K2100_const1, K2100_const2])
    K2100_theta = np.array([K2100_theta1, K2100_theta2])
    K1820_const = np.array([K1820_const1, K1820_const2])
    K1820_theta = np.array([K1820_theta1, K1820_theta2])
    K2250_const = np.array([K2250_const1, K2250_const2])
    K2250_theta = np.array([K2250_theta1, K2250_theta2])
    data_phif0_980 = calculate_BW_flatte980(
        phi_mass, phi_width, data_phi_kk,
        phif0_980_B_propagator_mass, phif0_980_B_propagator_g_kk, phif0_980_B_propagator_rg, data_f_kk,
        data_phif0_kk, phif0_980_const, phif0_980_theta
    )
    data_phif0_1710 = calculate_BW_BW(
        phi_mass, phi_width, data_phi_kk,
        phif0_1710_B_propagator_mass, phif0_1710_B_propagator_width, data_f_kk,
        data_phif0_kk, phif0_1710_const, phif0_1710_theta
    )
    data_phif2_1270 = calculate_BW_flatte1270(
        phi_mass, phi_width, data_phi_kk,
        phif2_1270_B_propagator_mass, phif2_1270_B_propagator_width, data_f_kk,
        data_phif2_kk, phif2_1270_const, phif2_1270_theta
    )
    data_phif2_1525 = calculate_BW_BW(
        phi_mass, phi_width, data_phi_kk,
        phif2_1525_B_propagator_mass, phif2_1525_B_propagator_width, data_f_kk,
        data_phif2_kk, phif2_1525_const, phif2_1525_theta
    )
    data_phif2_2150 = calculate_BW_BW(
        phi_mass, phi_width, data_phi_kk,
        phif2_2150_B_propagator_mass, phif2_2150_B_propagator_width, data_f_kk,
        data_phif2_kk, phif2_2150_const, phif2_2150_theta
    )
    data_phif2_2340 = calculate_BW_BW(
        phi_mass, phi_width, data_phi_kk,
        phif2_2340_B_propagator_mass, phif2_2340_B_propagator_width, data_f_kk,
        data_phif2_kk, phif2_2340_const, phif2_2340_theta
    )
    data_phif0_2470 = calculate_BW_BW(
        phi_mass, phi_width, data_phi_kk,
        phif0_2470_B_propagator_mass, phif0_2470_B_propagator_width, data_f_kk,
        data_phif0_kk, phif0_2470_const, phif0_2470_theta
    )
    data_K2100 = calculate_BW_BW(
        phi_mass, phi_width, data_phi_kk,
        K2100_B_propagator_mass, K2100_B_propagator_width, data_f_kk,
        data_K2100, K2100_const, K2100_theta
    )
    data_K1820 = calculate_BW_BW(
        phi_mass, phi_width, data_phi_kk,
        K1820_B_propagator_mass, K1820_B_propagator_width, data_f_kk,
        data_K1820, K1820_const, K1820_theta
    )
    data_K2250 = calculate_BW_BW(
        phi_mass, phi_width, data_phi_kk,
        K2250_B_propagator_mass, K2250_B_propagator_width, data_f_kk,
        data_K2250, K2250_const, K2250_theta
    )
    component_data_phif0_980 = component_BW_flatte980(
        phi_mass, phi_width, truth_phi_kk,
        phif0_980_B_propagator_mass, phif0_980_B_propagator_g_kk, phif0_980_B_propagator_rg, truth_f_kk,
        truth_phif0_kk, phif0_980_const, phif0_980_theta
    )
    component_data_phif0_1710 = component_BW_BW(
        phi_mass, phi_width, truth_phi_kk,
        phif0_1710_B_propagator_mass, phif0_1710_B_propagator_width, truth_f_kk,
        truth_phif0_kk, phif0_1710_const, phif0_1710_theta
    )
    component_data_phif2_1270 = component_BW_flatte1270(
        phi_mass, phi_width, truth_phi_kk,
        phif2_1270_B_propagator_mass, phif2_1270_B_propagator_width, truth_f_kk,
        truth_phif2_kk, phif2_1270_const, phif2_1270_theta
    )
    component_data_phif2_1525 = component_BW_BW(
        phi_mass, phi_width, truth_phi_kk,
        phif2_1525_B_propagator_mass, phif2_1525_B_propagator_width, truth_f_kk,
        truth_phif2_kk, phif2_1525_const, phif2_1525_theta
    )
    component_data_phif2_2150 = component_BW_BW(
        phi_mass, phi_width, truth_phi_kk,
        phif2_2150_B_propagator_mass, phif2_2150_B_propagator_width, truth_f_kk,
        truth_phif2_kk, phif2_2150_const, phif2_2150_theta
    )
    component_data_phif2_2340 = component_BW_BW(
        phi_mass, phi_width, truth_phi_kk,
        phif2_2340_B_propagator_mass, phif2_2340_B_propagator_width, truth_f_kk,
        truth_phif2_kk, phif2_2340_const, phif2_2340_theta
    )
    component_data_phif0_2470 = component_BW_BW(
        phi_mass, phi_width, truth_phi_kk,
        phif0_2470_B_propagator_mass, phif0_2470_B_propagator_width, truth_f_kk,
        truth_phif0_kk, phif0_2470_const, phif0_2470_theta
    )
    component_data_K2100 = component_BW_BW(
        phi_mass, phi_width, truth_phi_kk,
        K2100_B_propagator_mass, K2100_B_propagator_width, truth_f_kk,
        truth_K2100, K2100_const, K2100_theta
    )
    component_data_K1820 = component_BW_BW(
        phi_mass, phi_width, truth_phi_kk,
        K1820_B_propagator_mass, K1820_B_propagator_width, truth_f_kk,
        truth_K1820, K1820_const, K1820_theta
    )
    component_data_K2250 = component_BW_BW(
        phi_mass, phi_width, truth_phi_kk,
        K2250_B_propagator_mass, K2250_B_propagator_width, truth_f_kk,
        truth_K2250, K2250_const, K2250_theta
    )
    sum_frac = np.sum(dplex_dabs(
        np.einsum("mljk->mjk", component_data_phif0_980) +
        np.einsum("mljk->mjk", component_data_phif0_1710) +
        np.einsum("mljk->mjk", component_data_phif2_1270) +
        np.einsum("mljk->mjk", component_data_phif2_1525) +
        np.einsum("mljk->mjk", component_data_phif2_2150) +
        np.einsum("mljk->mjk", component_data_phif2_2340) +
        np.einsum("mljk->mjk", component_data_phif0_2470) +
        np.einsum("mljk->mjk", component_data_K2100) +
        np.einsum("mljk->mjk", component_data_K1820) +
        np.einsum("mljk->mjk", component_data_K2250)
    ))
    frac_phif0_980 = np.sum(np.einsum("ljk->l", dplex_dabs(component_data_phif0_980)) / sum_frac)
    frac_phif0_1710 = np.sum(np.einsum("ljk->l", dplex_dabs(component_data_phif0_1710)) / sum_frac)
    frac_phif2_1270 = np.sum(np.einsum("ljk->l", dplex_dabs(component_data_phif2_1270)) / sum_frac)
    frac_phif2_1525 = np.sum(np.einsum("ljk->l", dplex_dabs(component_data_phif2_1525)) / sum_frac)
    frac_phif2_2150 = np.sum(np.einsum("ljk->l", dplex_dabs(component_data_phif2_2150)) / sum_frac)
    frac_phif2_2340 = np.sum(np.einsum("ljk->l", dplex_dabs(component_data_phif2_2340)) / sum_frac)
    frac_phif0_2470 = np.sum(np.einsum("ljk->l", dplex_dabs(component_data_phif0_2470)) / sum_frac)
    frac_K2100 = np.sum(np.einsum("ljk->l", dplex_dabs(component_data_K2100)) / sum_frac)
    frac_K1820 = np.sum(np.einsum("ljk->l", dplex_dabs(component_data_K1820)) / sum_frac)
    frac_K2250 = np.sum(np.einsum("ljk->l", dplex_dabs(component_data_K2250)) / sum_frac)
    total_frac = frac_phif0_980 + frac_phif0_1710 + frac_phif2_1270 + frac_phif2_1525 + frac_phif2_2150 + frac_phif2_2340 + frac_phif0_2470 + frac_K2100 + frac_K1820 + frac_K2250
    step_function = np.power(total_frac - 1.03, 2.0) * constraint_strength
    total_amplitude = data_phif0_980
    total_amplitude = total_amplitude + data_phif0_1710
    total_amplitude = total_amplitude + data_phif2_1270
    total_amplitude = total_amplitude + data_phif2_1525
    total_amplitude = total_amplitude + data_phif2_2150
    total_amplitude = total_amplitude + data_phif2_2340
    total_amplitude = total_amplitude + data_phif0_2470
    total_amplitude = total_amplitude + data_K2100
    total_amplitude = total_amplitude + data_K1820
    total_amplitude = total_amplitude + data_K2250
    likelihood = -np.sum(np.log(np.sum(dplex_dabs(total_amplitude), axis=1))) + step_function
    return likelihood

def mc_likelihood_kk(args):
    params = extract_parameters(args)
    phif0_980_B_propagator_mass, phif0_980_B_propagator_g_kk, phif0_980_B_propagator_rg, phif0_980_const2, phif0_980_theta2, phif0_1710_B_propagator_mass, phif0_1710_B_propagator_width, phif0_1710_const1, phif0_1710_const2, phif0_1710_theta1, phif0_1710_theta2, phif2_1270_B_propagator_mass, phif2_1270_B_propagator_width, phif2_1270_const1, phif2_1270_const2, phif2_1270_const3, phif2_1270_const4, phif2_1270_const5, phif2_1270_theta1, phif2_1270_theta2, phif2_1270_theta3, phif2_1270_theta4, phif2_1270_theta5, phif2_1525_B_propagator_mass, phif2_1525_B_propagator_width, phif2_1525_const1, phif2_1525_const2, phif2_1525_const3, phif2_1525_const4, phif2_1525_const5, phif2_1525_theta1, phif2_1525_theta2, phif2_1525_theta3, phif2_1525_theta4, phif2_1525_theta5, phif2_2150_B_propagator_mass, phif2_2150_B_propagator_width, phif2_2150_const1, phif2_2150_const2, phif2_2150_const3, phif2_2150_const4, phif2_2150_const5, phif2_2150_theta1, phif2_2150_theta2, phif2_2150_theta3, phif2_2150_theta4, phif2_2150_theta5, phif2_2340_B_propagator_mass, phif2_2340_B_propagator_width, phif2_2340_const1, phif2_2340_const2, phif2_2340_const3, phif2_2340_const4, phif2_2340_const5, phif2_2340_theta1, phif2_2340_theta2, phif2_2340_theta3, phif2_2340_theta4, phif2_2340_theta5, phif0_2470_B_propagator_mass, phif0_2470_B_propagator_width, phif0_2470_const1, phif0_2470_const2, phif0_2470_theta1, phif0_2470_theta2, K2100_B_propagator_mass, K2100_B_propagator_width, K2100_const1, K2100_const2, K2100_theta1, K2100_theta2, K1820_B_propagator_mass, K1820_B_propagator_width, K1820_const1, K1820_const2, K1820_theta1, K1820_theta2, K2250_B_propagator_mass, K2250_B_propagator_width, K2250_const1, K2250_const2, K2250_theta1, K2250_theta2 = params
    phif0_980_const = np.array([1.0, phif0_980_const2])
    phif0_980_theta = np.array([0.0, phif0_980_theta2])
    phif0_1710_const = np.array([phif0_1710_const1, phif0_1710_const2])
    phif0_1710_theta = np.array([phif0_1710_theta1, phif0_1710_theta2])
    phif2_1270_const = np.array([phif2_1270_const1, phif2_1270_const2, phif2_1270_const3, phif2_1270_const4, phif2_1270_const5])
    phif2_1270_theta = np.array([phif2_1270_theta1, phif2_1270_theta2, phif2_1270_theta3, phif2_1270_theta4, phif2_1270_theta5])
    phif2_1525_const = np.array([phif2_1525_const1, phif2_1525_const2, phif2_1525_const3, phif2_1525_const4, phif2_1525_const5])
    phif2_1525_theta = np.array([phif2_1525_theta1, phif2_1525_theta2, phif2_1525_theta3, phif2_1525_theta4, phif2_1525_theta5])
    phif2_2150_const = np.array([phif2_2150_const1, phif2_2150_const2, phif2_2150_const3, phif2_2150_const4, phif2_2150_const5])
    phif2_2150_theta = np.array([phif2_2150_theta1, phif2_2150_theta2, phif2_2150_theta3, phif2_2150_theta4, phif2_2150_theta5])
    phif2_2340_const = np.array([phif2_2340_const1, phif2_2340_const2, phif2_2340_const3, phif2_2340_const4, phif2_2340_const5])
    phif2_2340_theta = np.array([phif2_2340_theta1, phif2_2340_theta2, phif2_2340_theta3, phif2_2340_theta4, phif2_2340_theta5])
    phif0_2470_const = np.array([phif0_2470_const1, phif0_2470_const2])
    phif0_2470_theta = np.array([phif0_2470_theta1, phif0_2470_theta2])
    K2100_const = np.array([K2100_const1, K2100_const2])
    K2100_theta = np.array([K2100_theta1, K2100_theta2])
    K1820_const = np.array([K1820_const1, K1820_const2])
    K1820_theta = np.array([K1820_theta1, K1820_theta2])
    K2250_const = np.array([K2250_const1, K2250_const2])
    K2250_theta = np.array([K2250_theta1, K2250_theta2])
    total_mc = calculate_BW_flatte980(
        phi_mass, phi_width, mc_phi_kk,
        phif0_980_B_propagator_mass, phif0_980_B_propagator_g_kk, phif0_980_B_propagator_rg, mc_f_kk,
        mc_phif0_kk, phif0_980_const, phif0_980_theta
    )
    total_mc = total_mc + calculate_BW_BW(
        phi_mass, phi_width, mc_phi_kk,
        phif0_1710_B_propagator_mass, phif0_1710_B_propagator_width, mc_f_kk,
        mc_phif0_kk, phif0_1710_const, phif0_1710_theta
    )
    total_mc = total_mc + calculate_BW_flatte1270(
        phi_mass, phi_width, mc_phi_kk,
        phif2_1270_B_propagator_mass, phif2_1270_B_propagator_width, mc_f_kk,
        mc_phif2_kk, phif2_1270_const, phif2_1270_theta
    )
    total_mc = total_mc + calculate_BW_BW(
        phi_mass, phi_width, mc_phi_kk,
        phif2_1525_B_propagator_mass, phif2_1525_B_propagator_width, mc_f_kk,
        mc_phif2_kk, phif2_1525_const, phif2_1525_theta
    )
    total_mc = total_mc + calculate_BW_BW(
        phi_mass, phi_width, mc_phi_kk,
        phif2_2150_B_propagator_mass, phif2_2150_B_propagator_width, mc_f_kk,
        mc_phif2_kk, phif2_2150_const, phif2_2150_theta
    )
    total_mc = total_mc + calculate_BW_BW(
        phi_mass, phi_width, mc_phi_kk,
        phif2_2340_B_propagator_mass, phif2_2340_B_propagator_width, mc_f_kk,
        mc_phif2_kk, phif2_2340_const, phif2_2340_theta
    )
    total_mc = total_mc + calculate_BW_BW(
        phi_mass, phi_width, mc_phi_kk,
        phif0_2470_B_propagator_mass, phif0_2470_B_propagator_width, mc_f_kk,
        mc_phif0_kk, phif0_2470_const, phif0_2470_theta
    )
    total_mc = total_mc + calculate_BW_BW(
        phi_mass, phi_width, mc_phi_kk,
        K2100_B_propagator_mass, K2100_B_propagator_width, mc_f_kk,
        mc_K2100, K2100_const, K2100_theta
    )
    total_mc = total_mc + calculate_BW_BW(
        phi_mass, phi_width, mc_phi_kk,
        K1820_B_propagator_mass, K1820_B_propagator_width, mc_f_kk,
        mc_K1820, K1820_const, K1820_theta
    )
    total_mc = total_mc + calculate_BW_BW(
        phi_mass, phi_width, mc_phi_kk,
        K2250_B_propagator_mass, K2250_B_propagator_width, mc_f_kk,
        mc_K2250, K2250_const, K2250_theta
    )
    return np.mean(np.sum(dplex_dabs(total_mc), axis=1))


def combined_likelihood(args):
    """组合似然函数: data_likelihood + datasize * log(mc_likelihood)"""
    data_lh = data_likelihood_kk(args)
    mc_lh = mc_likelihood_kk(args)
    combined_lh = data_lh + data_size * np.log(mc_lh)
    return combined_lh

def hvp_combined_likelihood(args, vector):
    """计算Hessian-vector product for combined likelihood"""
    return jvp(grad(combined_likelihood), [args], [vector])[1]



data = load_data()
data = normalize_data(data)
jax_data = prepare_data_for_jax(data)

data_phi_kk = jax_data['data_phi_kk']
data_f_kk = jax_data['data_f_kk']
data_kst2_124_kk = jax_data['data_kst2_124_kk']
data_kst2_123_kk = jax_data['data_kst2_123_kk']
data_phif0_kk = jax_data['data_phif0_kk']
data_phif2_kk = jax_data['data_phif2_kk']
data_u_kst2_r_kk = jax_data['data_u_kst2_r_kk']
data_u_kst2_l_kk = jax_data['data_u_kst2_l_kk']

mc_phi_kk = jax_data['mc_phi_kk']
mc_f_kk = jax_data['mc_f_kk']
mc_kst2_124_kk = jax_data['mc_kst2_124_kk']
mc_kst2_123_kk = jax_data['mc_kst2_123_kk']
mc_phif0_kk = jax_data['mc_phif0_kk']
mc_phif2_kk = jax_data['mc_phif2_kk']
mc_u_kst2_r_kk = jax_data['mc_u_kst2_r_kk']
mc_u_kst2_l_kk = jax_data['mc_u_kst2_l_kk']

truth_phi_kk = jax_data['truth_phi_kk']
truth_f_kk = jax_data['truth_f_kk']
truth_kst2_124_kk = jax_data['truth_kst2_124_kk']
truth_kst2_123_kk = jax_data['truth_kst2_123_kk']
truth_phif0_kk = jax_data['truth_phif0_kk']
truth_phif2_kk = jax_data['truth_phif2_kk']
truth_u_kst2_r_kk = jax_data['truth_u_kst2_r_kk']
truth_u_kst2_l_kk = jax_data['truth_u_kst2_l_kk']

wt_data_kk = jax_data['wt_data_kk']

data_size = len(data_phi_kk)

if __name__  == "__main__":
    """使用Newton-CG方法和HVP的拟合函数"""
    logger = setup_logging()
    logger.info("开始HVP优化版PWA拟合（Newton-CG方法）")

    config.update("jax_enable_x64", True)

    constraint_strength = 0.0

    logger.info("编译JAX函数（HVP版本）...")
    jit_likelihood = jit(combined_likelihood)
    jit_grad = jit(grad(combined_likelihood))
    jit_hvp = jit(hvp_combined_likelihood)

    test_result = jit_likelihood(args_list)
    logger.info(f"初始似然值: {test_result}")

    test_vector = onp.ones_like(args_list)
    test_hvp = jit_hvp(args_list, test_vector)
    logger.info(f"HVP测试完成，结果形状: {test_hvp.shape}")

    def my_callback(x):
        current_likelihood = jit_likelihood(x)
        logger.info(f"当前似然值: {current_likelihood}")

    def hessp(x, p):
        return onp.array(jit_hvp(x, p))

    logger.info("开始优化（Newton-CG + HVP）...")
    start_time = time.time()

    result = minimize(
        fun=lambda x: float(jit_likelihood(x)),
        x0=args_list,
        jac=lambda x: onp.array(jit_grad(x)),
        hessp=hessp,
        method="Newton-CG",
        callback=my_callback,
        options={"disp": False, "xtol": 1e-8}
    )

    end_time = time.time()

    logger.info("="*50)
    logger.info(f"HVP优化完成!")
    logger.info(f"成功: {result.success}")
    logger.info(f"最终似然值: {result.fun}")
    logger.info(f"迭代次数: {result.nit}")
    logger.info(f"函数调用次数: {result.nfev}")
    logger.info(f"梯度调用次数: {result.njev}")
    logger.info(f"Hessian调用次数: {result.nhev}")
    logger.info(f"优化时间: {end_time - start_time:.2f} 秒")
    logger.info(f"优化信息: {result.message}")
    logger.info("="*50)

    logger.info("计算参数误差（Hessian逆矩阵）...")
    args_size = args_list.shape[0]
    hessian_matrix = onp.zeros([args_size, args_size])
    for i in range(args_size):
        v = onp.zeros(args_size)
        v[i] = 1.0
        hessian_matrix[:, i] = onp.array(jit_hvp(result.x, v))
    ferror = onp.sqrt(onp.diag(onp.linalg.inv(hessian_matrix)))
    logger.info(f"误差计算完成")

    os.makedirs("output/fit", exist_ok=True)
    onp.save("output/fit/fit_result_values.npy", result.x)
    onp.save("output/fit/fit_result_errors.npy", ferror)
    logger.info("参数已保存至 output/fit/fit_result_values.npy")

    result_config = build_config(result.x, ferror)
    with open("output/fit/fit_result_config.json", "w", encoding="utf-8") as f:
        json.dump(result_config, f, indent=4)
    logger.info("配置已保存至 output/fit/fit_result_config.json")