# Auto-generated by LLMResonanceGenerator — do not edit manually
import copy
import json
import logging
import logging.config
import os
# must set before importing jax
os.environ["XLA_PYTHON_CLIENT_PREALLOCATE"] = "false"
import time
import numpy as onp
from functools import partial
from scipy.optimize import minimize

import jax.numpy as np
from jax import device_put, grad, jit, vmap, jvp
from jax import config



import sys
foo_path = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(foo_path)
sys.path.append(foo_path)



def setup_logging():
    """Setup logging configuration"""
    with open("config/logconfig_fit.json", "r") as config_file:
        LOGGING_CONFIG = json.load(config_file)
        logging.config.dictConfig(LOGGING_CONFIG)
    return logging.getLogger("fit")



def dplex_deinsum(subscript, aa, bb):
    real = np.einsum(subscript, aa[0], bb[0]) - np.einsum(subscript, aa[1], bb[1])
    imag = np.einsum(subscript, aa[0], bb[1]) + np.einsum(subscript, aa[1], bb[0])
    return np.stack([real, imag], axis=0)

def dplex_deinsum_ord(subscript, aa, bb):
    real = np.einsum(subscript, aa, bb[0])
    imag = np.einsum(subscript, aa, bb[1])
    return np.stack([real, imag], axis=0)

def dplex_dabs(aa):
    return aa[0]**2 + aa[1]**2 # 因为是纵向叠加所以aa[0]是纵向上第一个数组

def dplex_dtomine(aa):
    return np.stack([np.real(aa), np.imag(aa)], axis=0) # 组合而成的数组 axis=0 的第一个数组为实部，第二个数组为虚部

def dplex_dconstruct(aa, bb):
    return np.stack([aa, bb], axis=0) # 纵向叠加数组 第一维为实部，第二维为虚部

def dplex_ddivide(a, bb):
    real = a * bb[0] / dplex_dabs(bb)
    imag = -a * bb[1] / dplex_dabs(bb)
    return np.stack([real, imag], axis=0)


#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import jax.numpy as np

# ==============================================================================
# SECTION: PHYSICS_FUNCTIONS
# Physics calculation functions (resonance shape functions)
# Provided by the user for each analysis. Copy this file to your analysis
# directory as physics_functions.py and keep only the functions you need.
# ==============================================================================




def BW(m_, w_, Sbc):
    l = (Sbc.shape)[0]
    temp = dplex_dconstruct(m_*m_ - Sbc, -m_*w_*np.ones(l))
    return dplex_ddivide(1.0, temp)


def BW_relativity(m_, w_, Sbc):
    gamma = np.sqrt(m_*m_*(m_*m_+w_*w_))
    k = np.sqrt(2*np.sqrt(2)*m_*np.abs(w_)*gamma/np.pi/np.sqrt(m_*m_+gamma))
    l = (Sbc.shape)[0]
    temp = dplex_dconstruct(m_*m_ - Sbc, -m_*w_*np.ones(l))
    return dplex_ddivide(k, temp)


def flatte980(m_, g_pipi, rg, Sbc):
    g_kk = rg * g_pipi
    m_k = 0.493677
    m_pi = 0.13957061
    rho_kk = np.sqrt(np.abs(1 - 4*m_k*m_k / Sbc))
    rho_pipi = np.sqrt(np.abs(1 - 4*m_pi*m_pi / Sbc))
    tmp_A = dplex_dconstruct(m_**2 - Sbc, -1*(g_pipi*rho_pipi + g_kk*rho_kk))
    return dplex_ddivide(1.0, tmp_A)


def flatte1270(m_, w_, Sbc):
    rm = m_ * m_
    gr = m_ * w_
    q2r = 0.25 * rm - 0.0194792
    b2r = q2r * (q2r + 0.1825) + 0.033306
    g11270 = gr * b2r / np.power(q2r, 2.5)
    q2 = 0.25 * Sbc - 0.0194792
    b2 = q2 * (q2 + 0.1825) + 0.033306
    g1 = g11270 * np.power(q2, 2.5) / b2
    tmp = dplex_dconstruct(Sbc - rm, g1)
    return dplex_ddivide(gr, tmp)


def flatte500(m_, b1, b2, b3, b4, b5, Sbc):
    m2 = m_*m_
    rp = 0.139556995
    mpi2d2 = 0.009739946882
    cro1 = np.sqrt(np.abs((Sbc-(2*rp)**2)*Sbc))/Sbc
    cro2 = np.sqrt(np.abs((m2-(2*rp)**2)*m2))/m2
    pip1 = np.sqrt(np.abs(1.0 - 0.3116765584/Sbc))/(1.0+np.exp(9.8-3.5*Sbc))
    pip2 = np.sqrt(np.abs(1.0 - 0.3116765584/m2))/(1.0+np.exp(9.8-3.5*m2))
    cgam1 = m_*(b1+b2*Sbc)*(Sbc-mpi2d2)/(m2-mpi2d2)*np.exp(-(Sbc-m2)/b3)*cro1/cro2
    cgam2 = m_*b4*pip1/pip2
    tmp = dplex_dconstruct(m2-Sbc, -b5*(cgam1+cgam2))
    return dplex_ddivide(1.0, tmp)


def load_data():
    data = {}

    # Load real data
    data['data_phi_kk'] = onp.load("data/real_data/phi_kk.npy")
    data['data_f_kk'] = onp.load("data/real_data/f_kk.npy")
    data['data_kst2_124_kk'] = onp.load("data/real_data/kst2_124_kk.npy")
    data['data_kst2_123_kk'] = onp.load("data/real_data/kst2_123_kk.npy")
    data['data_phif0_kk'] = onp.load("data/real_data/phif0_kk.npy")
    data['data_phif2_kk'] = onp.load("data/real_data/phif2_kk.npy")
    data['data_u_kst2_r_kk'] = onp.load("data/real_data/u_kst2_r_kk.npy")
    data['data_u_kst2_l_kk'] = onp.load("data/real_data/u_kst2_l_kk.npy")

    # Load MC data
    data['mc_phi_kk'] = onp.load("data/mc_truth/phi_kk.npy")
    data['mc_f_kk'] = onp.load("data/mc_truth/f_kk.npy")
    data['mc_kst2_124_kk'] = onp.load("data/mc_truth/kst2_124_kk.npy")
    data['mc_kst2_123_kk'] = onp.load("data/mc_truth/kst2_123_kk.npy")
    data['mc_phif0_kk'] = onp.load("data/mc_truth/phif0_kk.npy")
    data['mc_phif2_kk'] = onp.load("data/mc_truth/phif2_kk.npy")
    data['mc_u_kst2_r_kk'] = onp.load("data/mc_truth/u_kst2_r_kk.npy")
    data['mc_u_kst2_l_kk'] = onp.load("data/mc_truth/u_kst2_l_kk.npy")

    # MC truth data (for constraints)
    data['truth_phi_kk'] = data['mc_phi_kk'][0:150000]
    data['truth_f_kk'] = data['mc_f_kk'][0:150000]
    data['truth_kst2_124_kk'] = data['mc_kst2_124_kk'][0:150000]
    data['truth_kst2_123_kk'] = data['mc_kst2_123_kk'][0:150000]
    data['truth_phif0_kk'] = data['mc_phif0_kk'][:, 0:150000]
    data['truth_phif2_kk'] = data['mc_phif2_kk'][:, 0:150000]
    data['truth_u_kst2_r_kk'] = data['mc_u_kst2_r_kk'][:, 0:150000]
    data['truth_u_kst2_l_kk'] = data['mc_u_kst2_l_kk'][:, 0:150000]

    # Weight data
    try:
        data['wt_data_kk'] = onp.load("data/weight/weight_kk.npy")
    except FileNotFoundError:
        data['wt_data_kk'] = onp.ones_like(data['data_phi_kk'])

    return data

def normalize_data(data):
    # 计算归一化因子
    regular_phif0_kk = 1. / onp.average(
        onp.sqrt(onp.sum(onp.asarray(data['mc_phif0_kk'])**2, axis=2)), axis=1
    )
    regular_phif2_kk = 1. / onp.average(
        onp.sqrt(onp.sum(onp.asarray(data['mc_phif2_kk'])**2, axis=2)), axis=1
    )
    regular_u_kst2_r_kk = 1. / onp.average(
        onp.sqrt(onp.sum(onp.asarray(data['mc_u_kst2_r_kk'])**2, axis=2)), axis=1
    )
    regular_u_kst2_l_kk = 1. / onp.average(
        onp.sqrt(onp.sum(onp.asarray(data['mc_u_kst2_l_kk'])**2, axis=2)), axis=1
    )

    # 应用归一化
    data['data_phif0_kk'] = onp.einsum("jkl,j->jkl", data['data_phif0_kk'], regular_phif0_kk)
    data['mc_phif0_kk'] = onp.einsum("jkl,j->jkl", data['mc_phif0_kk'], regular_phif0_kk)
    data['truth_phif0_kk'] = onp.einsum("jkl,j->jkl", data['truth_phif0_kk'], regular_phif0_kk)
    data['data_phif2_kk'] = onp.einsum("jkl,j->jkl", data['data_phif2_kk'], regular_phif2_kk)
    data['mc_phif2_kk'] = onp.einsum("jkl,j->jkl", data['mc_phif2_kk'], regular_phif2_kk)
    data['truth_phif2_kk'] = onp.einsum("jkl,j->jkl", data['truth_phif2_kk'], regular_phif2_kk)
    data['data_u_kst2_r_kk'] = onp.einsum("jkl,j->jkl", data['data_u_kst2_r_kk'], regular_u_kst2_r_kk)
    data['mc_u_kst2_r_kk'] = onp.einsum("jkl,j->jkl", data['mc_u_kst2_r_kk'], regular_u_kst2_r_kk)
    data['truth_u_kst2_r_kk'] = onp.einsum("jkl,j->jkl", data['truth_u_kst2_r_kk'], regular_u_kst2_r_kk)
    data['data_u_kst2_l_kk'] = onp.einsum("jkl,j->jkl", data['data_u_kst2_l_kk'], regular_u_kst2_l_kk)
    data['mc_u_kst2_l_kk'] = onp.einsum("jkl,j->jkl", data['mc_u_kst2_l_kk'], regular_u_kst2_l_kk)
    data['truth_u_kst2_l_kk'] = onp.einsum("jkl,j->jkl", data['truth_u_kst2_l_kk'], regular_u_kst2_l_kk)

    return data

def prepare_data_for_jax(data, device=None):
    jax_data = {}
    for key, value in data.items():
        jax_data[key] = device_put(np.array(value), device=device)
    return jax_data

def calculate_BW_BW(A_mass, A_width, phi_kk, B_mass, B_width, f_kk, Amplitude_param_AMP, Amplitude_param_const, Amplitude_param_theta):
    A_propagator = BW(A_mass, A_width, phi_kk)
    B_propagator = np.moveaxis(
        vmap(partial(BW, Sbc=f_kk))(B_mass, B_width), 1, 0
    )
    propagator_combined = dplex_deinsum("j, ij->ij", A_propagator, B_propagator)
    const_ph = dplex_dconstruct(Amplitude_param_const, Amplitude_param_theta)
    result = dplex_deinsum_ord("ijk,li->ljk", Amplitude_param_AMP, const_ph)
    result = dplex_deinsum("ljk,lj->jk", result, propagator_combined)
    return result

def component_BW_BW(A_mass, A_width, phi_kk, B_mass, B_width, f_kk, Amplitude_param_AMP, Amplitude_param_const, Amplitude_param_theta):
    A_propagator = BW(A_mass, A_width, phi_kk)
    B_propagator = np.moveaxis(
        vmap(partial(BW, Sbc=f_kk))(B_mass, B_width), 1, 0
    )
    propagator_combined = dplex_deinsum("j, ij->ij", A_propagator, B_propagator)
    const_ph = dplex_dconstruct(Amplitude_param_const, Amplitude_param_theta)
    result = dplex_deinsum_ord("ijk,li->ljk", Amplitude_param_AMP, const_ph)
    result = dplex_deinsum("ljk,lj->ljk", result, propagator_combined)
    return result

def calculate_BW_flatte980(A_mass, A_width, phi_kk, B_mass, B_g_kk, B_rg, f_kk, Amplitude_param_AMP, Amplitude_param_const, Amplitude_param_theta):
    A_propagator = BW(A_mass, A_width, phi_kk)
    B_propagator = flatte980(B_mass, B_g_kk, B_rg, f_kk)
    propagator_combined = dplex_deinsum("j, j->j", A_propagator, B_propagator)
    const_ph = dplex_dconstruct(Amplitude_param_const, Amplitude_param_theta)
    result = dplex_deinsum_ord("ijk,li->ljk", Amplitude_param_AMP, const_ph)
    result = dplex_deinsum("ljk,j->jk", result, propagator_combined)
    return result

def component_BW_flatte980(A_mass, A_width, phi_kk, B_mass, B_g_kk, B_rg, f_kk, Amplitude_param_AMP, Amplitude_param_const, Amplitude_param_theta):
    A_propagator = BW(A_mass, A_width, phi_kk)
    B_propagator = flatte980(B_mass, B_g_kk, B_rg, f_kk)
    propagator_combined = dplex_deinsum("j, j->j", A_propagator, B_propagator)
    const_ph = dplex_dconstruct(Amplitude_param_const, Amplitude_param_theta)
    result = dplex_deinsum_ord("ijk,li->ljk", Amplitude_param_AMP, const_ph)
    result = dplex_deinsum("ljk,j->ljk", result, propagator_combined)
    return result

def calculate_BW_flatte1270(A_mass, A_width, phi_kk, B_mass, B_width, f_kk, Amplitude_param_AMP, Amplitude_param_const, Amplitude_param_theta):
    A_propagator = BW(A_mass, A_width, phi_kk)
    B_propagator = flatte1270(B_mass, B_width, f_kk)
    propagator_combined = dplex_deinsum("j, j->j", A_propagator, B_propagator)
    const_ph = dplex_dconstruct(Amplitude_param_const, Amplitude_param_theta)
    result = dplex_deinsum_ord("ijk,li->ljk", Amplitude_param_AMP, const_ph)
    result = dplex_deinsum("ljk,j->jk", result, propagator_combined)
    return result

def component_BW_flatte1270(A_mass, A_width, phi_kk, B_mass, B_width, f_kk, Amplitude_param_AMP, Amplitude_param_const, Amplitude_param_theta):
    A_propagator = BW(A_mass, A_width, phi_kk)
    B_propagator = flatte1270(B_mass, B_width, f_kk)
    propagator_combined = dplex_deinsum("j, j->j", A_propagator, B_propagator)
    const_ph = dplex_dconstruct(Amplitude_param_const, Amplitude_param_theta)
    result = dplex_deinsum_ord("ijk,li->ljk", Amplitude_param_AMP, const_ph)
    result = dplex_deinsum("ljk,j->ljk", result, propagator_combined)
    return result

def make_initial_args():
    return onp.array([
        0.9794812115574156,  # resonances.phif0_980.propagators.B_propagator.mass
        0.10678616326827592,  # resonances.phif0_980.propagators.B_propagator.g_kk
        8.570187550432664,  # resonances.phif0_980.propagators.B_propagator.rg
        0.1065182971468388,  # resonances.phif0_980.Amplitude.const2
        0.03807025376236671,  # resonances.phif0_980.Amplitude.theta2
        1.6761965590304995,  # resonances.phif0_1710.propagators.B_propagator.mass
        0.16270071108440043,  # resonances.phif0_1710.propagators.B_propagator.width
        0.02201375198386279,  # resonances.phif0_1710.Amplitude.const1
        0.007433204877151768,  # resonances.phif0_1710.Amplitude.const2
        0.008302300118288414,  # resonances.phif0_1710.Amplitude.theta1
        -0.018544178045626723,  # resonances.phif0_1710.Amplitude.theta2
        1.2896149318644679,  # resonances.phif2_1270.propagators.B_propagator.mass
        0.1959796900380022,  # resonances.phif2_1270.propagators.B_propagator.width
        -0.013533706721054747,  # resonances.phif2_1270.Amplitude.const1
        -0.01650921272412254,  # resonances.phif2_1270.Amplitude.const2
        0.015339403283337268,  # resonances.phif2_1270.Amplitude.const3
        0.029798824827026338,  # resonances.phif2_1270.Amplitude.const4
        0.020982478502465995,  # resonances.phif2_1270.Amplitude.const5
        0.05458389002821978,  # resonances.phif2_1270.Amplitude.theta1
        0.016032334798079934,  # resonances.phif2_1270.Amplitude.theta2
        0.017179622009723918,  # resonances.phif2_1270.Amplitude.theta3
        -0.050143087437086675,  # resonances.phif2_1270.Amplitude.theta4
        -0.008718872479379924,  # resonances.phif2_1270.Amplitude.theta5
        1.5222602842746435,  # resonances.phif2_1525.propagators.B_propagator.mass
        0.08576525399315078,  # resonances.phif2_1525.propagators.B_propagator.width
        -0.005345214125595505,  # resonances.phif2_1525.Amplitude.const1
        0.0031770703345810553,  # resonances.phif2_1525.Amplitude.const2
        -0.0036743677603351056,  # resonances.phif2_1525.Amplitude.const3
        0.004813366936315499,  # resonances.phif2_1525.Amplitude.const4
        0.010000673114238258,  # resonances.phif2_1525.Amplitude.const5
        -0.010529063356530807,  # resonances.phif2_1525.Amplitude.theta1
        0.003910028530572422,  # resonances.phif2_1525.Amplitude.theta2
        0.0031787953173277725,  # resonances.phif2_1525.Amplitude.theta3
        0.0333658928584713,  # resonances.phif2_1525.Amplitude.theta4
        -0.006053516058970728,  # resonances.phif2_1525.Amplitude.theta5
        2.1619576785269476,  # resonances.phif2_2150.propagators.B_propagator.mass
        0.15906049251159413,  # resonances.phif2_2150.propagators.B_propagator.width
        0.004643720949518616,  # resonances.phif2_2150.Amplitude.const1
        -0.0009682564746806725,  # resonances.phif2_2150.Amplitude.const2
        -0.0029804674908844213,  # resonances.phif2_2150.Amplitude.const3
        0.008315390493289363,  # resonances.phif2_2150.Amplitude.const4
        0.0005819695034846763,  # resonances.phif2_2150.Amplitude.const5
        0.00545992748088964,  # resonances.phif2_2150.Amplitude.theta1
        -0.012498776031677225,  # resonances.phif2_2150.Amplitude.theta2
        0.002196563552197887,  # resonances.phif2_2150.Amplitude.theta3
        -0.016814307435916394,  # resonances.phif2_2150.Amplitude.theta4
        -0.007232946300343621,  # resonances.phif2_2150.Amplitude.theta5
        2.547889297662712,  # resonances.phif2_2340.propagators.B_propagator.mass
        0.324001266488012,  # resonances.phif2_2340.propagators.B_propagator.width
        -0.15266341362240637,  # resonances.phif2_2340.Amplitude.const1
        -0.05030214288962155,  # resonances.phif2_2340.Amplitude.const2
        -0.01856511044577769,  # resonances.phif2_2340.Amplitude.const3
        0.0908719088071242,  # resonances.phif2_2340.Amplitude.const4
        0.029544599934778714,  # resonances.phif2_2340.Amplitude.const5
        0.06277085590848677,  # resonances.phif2_2340.Amplitude.theta1
        -0.0031366601030189344,  # resonances.phif2_2340.Amplitude.theta2
        0.13756083806604205,  # resonances.phif2_2340.Amplitude.theta3
        -0.0033564526519642953,  # resonances.phif2_2340.Amplitude.theta4
        0.06849361819185686,  # resonances.phif2_2340.Amplitude.theta5
        2.57497529295397,  # resonances.phif0_2470.propagators.B_propagator.mass
        0.15761784400243628,  # resonances.phif0_2470.propagators.B_propagator.width
        -0.345074426966773,  # resonances.phif0_2470.Amplitude.const1
        -0.15428119408751656,  # resonances.phif0_2470.Amplitude.const2
        0.2290031973516395,  # resonances.phif0_2470.Amplitude.theta1
        -0.13412740539296167,  # resonances.phif0_2470.Amplitude.theta2
        2.0945745764239794,  # resonances.K2100.propagators.B_propagator.mass
        0.1111549213189184,  # resonances.K2100.propagators.B_propagator.width
        0.00668002974985798,  # resonances.K2100.shared_amplitude_parameters.const1
        0.004965565274392332,  # resonances.K2100.shared_amplitude_parameters.const2
        -0.014345480981877965,  # resonances.K2100.shared_amplitude_parameters.theta1
        -0.004182231968927211,  # resonances.K2100.shared_amplitude_parameters.theta2
        1.8192837147853098,  # resonances.K1820.propagators.B_propagator.mass
        0.2552907595714486,  # resonances.K1820.propagators.B_propagator.width
        0.05353392339205181,  # resonances.K1820.shared_amplitude_parameters.const1
        -0.013515632832936594,  # resonances.K1820.shared_amplitude_parameters.const2
        -0.029170417788916315,  # resonances.K1820.shared_amplitude_parameters.theta1
        0.008796315351616747,  # resonances.K1820.shared_amplitude_parameters.theta2
        2.228180871519652,  # resonances.K2250.propagators.B_propagator.mass
        0.22526773581883117,  # resonances.K2250.propagators.B_propagator.width
        -0.021627369735391727,  # resonances.K2250.shared_amplitude_parameters.const1
        0.0034149684028485067,  # resonances.K2250.shared_amplitude_parameters.const2
        -0.03739773648153083,  # resonances.K2250.shared_amplitude_parameters.theta1
        0.005079738018594662,  # resonances.K2250.shared_amplitude_parameters.theta2
    ])

import numpy as np

def extract_parameters(args):
    return {
        'phi_mass': np.array([1.02]),
        'phi_width': np.array([0.004]),
        'u_kst2_r_kk_BW_BW_mass': np.array([args[65], args[71], args[77]]),
        'u_kst2_r_kk_BW_BW_width': np.array([args[66], args[72], args[78]]),
        'u_kst2_r_kk_BW_BW_const': np.array([args[67], args[68],
                                             args[73], args[74],
                                             args[79], args[80]]).reshape(-1, 2),
        'u_kst2_r_kk_BW_BW_theta': np.array([args[69], args[70],
                                             args[75], args[76],
                                             args[81], args[82]]).reshape(-1, 2),
        'u_kst2_l_kk_BW_BW_mass': np.array([args[65], args[71], args[77]]),
        'u_kst2_l_kk_BW_BW_width': np.array([args[66], args[72], args[78]]),
        'u_kst2_l_kk_BW_BW_const': np.array([args[67], args[68],
                                             args[73], args[74],
                                             args[79], args[80]]).reshape(-1, 2),
        'u_kst2_l_kk_BW_BW_theta': np.array([args[69], args[70],
                                             args[75], args[76],
                                             args[81], args[82]]).reshape(-1, 2),
        'phif0_kk_BW_flatte980_mass': np.array([args[0]]),
        'phif0_kk_BW_flatte980_g_kk': np.array([args[1]]),
        'phif0_kk_BW_flatte980_rg': np.array([args[2]]),
        'phif0_kk_BW_flatte980_const': np.array([0.1, args[3]]).reshape(-1, 2),
        'phif0_kk_BW_flatte980_theta': np.array([0.1, args[4]]).reshape(-1, 2),
        'phif0_kk_BW_BW_mass': np.array([args[5], args[59]]),
        'phif0_kk_BW_BW_width': np.array([args[6], args[60]]),
        'phif0_kk_BW_BW_const': np.array([args[7], args[8],
                                          args[61], args[62]]).reshape(-1, 2),
        'phif0_kk_BW_BW_theta': np.array([args[9], args[10],
                                          args[63], args[64]]).reshape(-1, 2),
        'phif2_kk_BW_flatte1270_mass': np.array([args[11]]),
        'phif2_kk_BW_flatte1270_width': np.array([args[12]]),
        'phif2_kk_BW_flatte1270_const': np.array([args[13], args[14], args[15], args[16], args[17]]).reshape(-1, 5),
        'phif2_kk_BW_flatte1270_theta': np.array([args[18], args[19], args[20], args[21], args[22]]).reshape(-1, 5),
        'phif2_kk_BW_BW_mass': np.array([args[23], args[35], args[47]]),
        'phif2_kk_BW_BW_width': np.array([args[24], args[36], args[48]]),
        'phif2_kk_BW_BW_const': np.array([args[25], args[26], args[27], args[28], args[29],
                                          args[37], args[38], args[39], args[40], args[41],
                                          args[49], args[50], args[51], args[52], args[53]]).reshape(-1, 5),
        'phif2_kk_BW_BW_theta': np.array([args[30], args[31], args[32], args[33], args[34],
                                          args[42], args[43], args[44], args[45], args[46],
                                          args[54], args[55], args[56], args[57], args[58]]).reshape(-1, 5),
    }

def save_results(args, errors, output_path):
    import toml, os
    records = []
    rec = {
        'path': 'resonances.phif0_980.propagators.B_propagator.mass',
        'value': float(args[0]),
        'range': [0.98, 10.0],
        'error': float(errors[0]),
        'arg_index': 0,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif0_980.propagators.B_propagator.g_kk',
        'value': float(args[1]),
        'error': float(errors[1]),
        'arg_index': 1,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif0_980.propagators.B_propagator.rg',
        'value': float(args[2]),
        'error': float(errors[2]),
        'arg_index': 2,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif0_980.Amplitude.const2',
        'value': float(args[3]),
        'error': float(errors[3]),
        'arg_index': 3,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif0_980.Amplitude.theta2',
        'value': float(args[4]),
        'error': float(errors[4]),
        'arg_index': 4,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif0_1710.propagators.B_propagator.mass',
        'value': float(args[5]),
        'range': [1.704, 1.0],
        'error': float(errors[5]),
        'arg_index': 5,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif0_1710.propagators.B_propagator.width',
        'value': float(args[6]),
        'range': [0.123, 1.0],
        'error': float(errors[6]),
        'arg_index': 6,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif0_1710.Amplitude.const1',
        'value': float(args[7]),
        'error': float(errors[7]),
        'arg_index': 7,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif0_1710.Amplitude.const2',
        'value': float(args[8]),
        'error': float(errors[8]),
        'arg_index': 8,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif0_1710.Amplitude.theta1',
        'value': float(args[9]),
        'error': float(errors[9]),
        'arg_index': 9,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif0_1710.Amplitude.theta2',
        'value': float(args[10]),
        'error': float(errors[10]),
        'arg_index': 10,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_1270.propagators.B_propagator.mass',
        'value': float(args[11]),
        'range': [1.2755, 1.0],
        'error': float(errors[11]),
        'arg_index': 11,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_1270.propagators.B_propagator.width',
        'value': float(args[12]),
        'range': [0.1867, 1.0],
        'error': float(errors[12]),
        'arg_index': 12,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_1270.Amplitude.const1',
        'value': float(args[13]),
        'error': float(errors[13]),
        'arg_index': 13,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_1270.Amplitude.const2',
        'value': float(args[14]),
        'error': float(errors[14]),
        'arg_index': 14,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_1270.Amplitude.const3',
        'value': float(args[15]),
        'error': float(errors[15]),
        'arg_index': 15,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_1270.Amplitude.const4',
        'value': float(args[16]),
        'error': float(errors[16]),
        'arg_index': 16,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_1270.Amplitude.const5',
        'value': float(args[17]),
        'error': float(errors[17]),
        'arg_index': 17,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_1270.Amplitude.theta1',
        'value': float(args[18]),
        'error': float(errors[18]),
        'arg_index': 18,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_1270.Amplitude.theta2',
        'value': float(args[19]),
        'error': float(errors[19]),
        'arg_index': 19,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_1270.Amplitude.theta3',
        'value': float(args[20]),
        'error': float(errors[20]),
        'arg_index': 20,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_1270.Amplitude.theta4',
        'value': float(args[21]),
        'error': float(errors[21]),
        'arg_index': 21,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_1270.Amplitude.theta5',
        'value': float(args[22]),
        'error': float(errors[22]),
        'arg_index': 22,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_1525.propagators.B_propagator.mass',
        'value': float(args[23]),
        'range': [1.517, 1.0],
        'error': float(errors[23]),
        'arg_index': 23,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_1525.propagators.B_propagator.width',
        'value': float(args[24]),
        'range': [0.086, 1.0],
        'error': float(errors[24]),
        'arg_index': 24,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_1525.Amplitude.const1',
        'value': float(args[25]),
        'error': float(errors[25]),
        'arg_index': 25,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_1525.Amplitude.const2',
        'value': float(args[26]),
        'error': float(errors[26]),
        'arg_index': 26,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_1525.Amplitude.const3',
        'value': float(args[27]),
        'error': float(errors[27]),
        'arg_index': 27,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_1525.Amplitude.const4',
        'value': float(args[28]),
        'error': float(errors[28]),
        'arg_index': 28,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_1525.Amplitude.const5',
        'value': float(args[29]),
        'error': float(errors[29]),
        'arg_index': 29,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_1525.Amplitude.theta1',
        'value': float(args[30]),
        'error': float(errors[30]),
        'arg_index': 30,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_1525.Amplitude.theta2',
        'value': float(args[31]),
        'error': float(errors[31]),
        'arg_index': 31,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_1525.Amplitude.theta3',
        'value': float(args[32]),
        'error': float(errors[32]),
        'arg_index': 32,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_1525.Amplitude.theta4',
        'value': float(args[33]),
        'error': float(errors[33]),
        'arg_index': 33,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_1525.Amplitude.theta5',
        'value': float(args[34]),
        'error': float(errors[34]),
        'arg_index': 34,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_2150.propagators.B_propagator.mass',
        'value': float(args[35]),
        'range': [2.157, 1.0],
        'error': float(errors[35]),
        'arg_index': 35,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_2150.propagators.B_propagator.width',
        'value': float(args[36]),
        'range': [0.152, 1.0],
        'error': float(errors[36]),
        'arg_index': 36,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_2150.Amplitude.const1',
        'value': float(args[37]),
        'error': float(errors[37]),
        'arg_index': 37,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_2150.Amplitude.const2',
        'value': float(args[38]),
        'error': float(errors[38]),
        'arg_index': 38,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_2150.Amplitude.const3',
        'value': float(args[39]),
        'error': float(errors[39]),
        'arg_index': 39,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_2150.Amplitude.const4',
        'value': float(args[40]),
        'error': float(errors[40]),
        'arg_index': 40,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_2150.Amplitude.const5',
        'value': float(args[41]),
        'error': float(errors[41]),
        'arg_index': 41,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_2150.Amplitude.theta1',
        'value': float(args[42]),
        'error': float(errors[42]),
        'arg_index': 42,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_2150.Amplitude.theta2',
        'value': float(args[43]),
        'error': float(errors[43]),
        'arg_index': 43,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_2150.Amplitude.theta3',
        'value': float(args[44]),
        'error': float(errors[44]),
        'arg_index': 44,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_2150.Amplitude.theta4',
        'value': float(args[45]),
        'error': float(errors[45]),
        'arg_index': 45,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_2150.Amplitude.theta5',
        'value': float(args[46]),
        'error': float(errors[46]),
        'arg_index': 46,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_2340.propagators.B_propagator.mass',
        'value': float(args[47]),
        'range': [2.345, 0.01],
        'error': float(errors[47]),
        'arg_index': 47,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_2340.propagators.B_propagator.width',
        'value': float(args[48]),
        'range': [0.322, 1.0],
        'error': float(errors[48]),
        'arg_index': 48,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_2340.Amplitude.const1',
        'value': float(args[49]),
        'error': float(errors[49]),
        'arg_index': 49,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_2340.Amplitude.const2',
        'value': float(args[50]),
        'error': float(errors[50]),
        'arg_index': 50,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_2340.Amplitude.const3',
        'value': float(args[51]),
        'error': float(errors[51]),
        'arg_index': 51,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_2340.Amplitude.const4',
        'value': float(args[52]),
        'error': float(errors[52]),
        'arg_index': 52,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_2340.Amplitude.const5',
        'value': float(args[53]),
        'error': float(errors[53]),
        'arg_index': 53,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_2340.Amplitude.theta1',
        'value': float(args[54]),
        'error': float(errors[54]),
        'arg_index': 54,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_2340.Amplitude.theta2',
        'value': float(args[55]),
        'error': float(errors[55]),
        'arg_index': 55,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_2340.Amplitude.theta3',
        'value': float(args[56]),
        'error': float(errors[56]),
        'arg_index': 56,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_2340.Amplitude.theta4',
        'value': float(args[57]),
        'error': float(errors[57]),
        'arg_index': 57,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif2_2340.Amplitude.theta5',
        'value': float(args[58]),
        'error': float(errors[58]),
        'arg_index': 58,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif0_2470.propagators.B_propagator.mass',
        'value': float(args[59]),
        'range': [2.47, 0.007],
        'error': float(errors[59]),
        'arg_index': 59,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif0_2470.propagators.B_propagator.width',
        'value': float(args[60]),
        'range': [0.075, 0.011],
        'error': float(errors[60]),
        'arg_index': 60,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif0_2470.Amplitude.const1',
        'value': float(args[61]),
        'error': float(errors[61]),
        'arg_index': 61,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif0_2470.Amplitude.const2',
        'value': float(args[62]),
        'error': float(errors[62]),
        'arg_index': 62,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif0_2470.Amplitude.theta1',
        'value': float(args[63]),
        'error': float(errors[63]),
        'arg_index': 63,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.phif0_2470.Amplitude.theta2',
        'value': float(args[64]),
        'error': float(errors[64]),
        'arg_index': 64,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.K2100.propagators.B_propagator.mass',
        'value': float(args[65]),
        'range': [2.1, 10.0],
        'error': float(errors[65]),
        'arg_index': 65,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.K2100.propagators.B_propagator.width',
        'value': float(args[66]),
        'range': [0.1, 10.0],
        'error': float(errors[66]),
        'arg_index': 66,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.K2100.shared_amplitude_parameters.const1',
        'value': float(args[67]),
        'error': float(errors[67]),
        'arg_index': 67,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.K2100.shared_amplitude_parameters.const2',
        'value': float(args[68]),
        'error': float(errors[68]),
        'arg_index': 68,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.K2100.shared_amplitude_parameters.theta1',
        'value': float(args[69]),
        'error': float(errors[69]),
        'arg_index': 69,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.K2100.shared_amplitude_parameters.theta2',
        'value': float(args[70]),
        'error': float(errors[70]),
        'arg_index': 70,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.K1820.propagators.B_propagator.mass',
        'value': float(args[71]),
        'range': [1.819, 10.0],
        'error': float(errors[71]),
        'arg_index': 71,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.K1820.propagators.B_propagator.width',
        'value': float(args[72]),
        'range': [0.264, 10.0],
        'error': float(errors[72]),
        'arg_index': 72,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.K1820.shared_amplitude_parameters.const1',
        'value': float(args[73]),
        'error': float(errors[73]),
        'arg_index': 73,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.K1820.shared_amplitude_parameters.const2',
        'value': float(args[74]),
        'error': float(errors[74]),
        'arg_index': 74,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.K1820.shared_amplitude_parameters.theta1',
        'value': float(args[75]),
        'error': float(errors[75]),
        'arg_index': 75,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.K1820.shared_amplitude_parameters.theta2',
        'value': float(args[76]),
        'error': float(errors[76]),
        'arg_index': 76,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.K2250.propagators.B_propagator.mass',
        'value': float(args[77]),
        'range': [2.247, 10.0],
        'error': float(errors[77]),
        'arg_index': 77,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.K2250.propagators.B_propagator.width',
        'value': float(args[78]),
        'range': [0.18, 10.0],
        'error': float(errors[78]),
        'arg_index': 78,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.K2250.shared_amplitude_parameters.const1',
        'value': float(args[79]),
        'error': float(errors[79]),
        'arg_index': 79,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.K2250.shared_amplitude_parameters.const2',
        'value': float(args[80]),
        'error': float(errors[80]),
        'arg_index': 80,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.K2250.shared_amplitude_parameters.theta1',
        'value': float(args[81]),
        'error': float(errors[81]),
        'arg_index': 81,
    }
    records.append(rec)
    rec = {
        'path': 'resonances.K2250.shared_amplitude_parameters.theta2',
        'value': float(args[82]),
        'error': float(errors[82]),
        'arg_index': 82,
    }
    records.append(rec)
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        toml.dump({'free_params': records}, f)

def data_likelihood_kk(args):
    params = extract_parameters(args)
    data_phif0_kk_BW_flatte980 = calculate_BW_flatte980(
        params['phi_mass'], params['phi_width'], data_phi_kk,
        params['phif0_kk_BW_flatte980_mass'], params['phif0_kk_BW_flatte980_g_kk'], params['phif0_kk_BW_flatte980_rg'], data_f_kk,
        data_phif0_kk, params['phif0_kk_BW_flatte980_const'], params['phif0_kk_BW_flatte980_theta']
    )
    data_phif0_kk_BW_BW = calculate_BW_BW(
        params['phi_mass'], params['phi_width'], data_phi_kk,
        params['phif0_kk_BW_BW_mass'], params['phif0_kk_BW_BW_width'], data_f_kk,
        data_phif0_kk, params['phif0_kk_BW_BW_const'], params['phif0_kk_BW_BW_theta']
    )
    data_phif2_kk_BW_flatte1270 = calculate_BW_flatte1270(
        params['phi_mass'], params['phi_width'], data_phi_kk,
        params['phif2_kk_BW_flatte1270_mass'], params['phif2_kk_BW_flatte1270_width'], data_f_kk,
        data_phif2_kk, params['phif2_kk_BW_flatte1270_const'], params['phif2_kk_BW_flatte1270_theta']
    )
    data_phif2_kk_BW_BW = calculate_BW_BW(
        params['phi_mass'], params['phi_width'], data_phi_kk,
        params['phif2_kk_BW_BW_mass'], params['phif2_kk_BW_BW_width'], data_f_kk,
        data_phif2_kk, params['phif2_kk_BW_BW_const'], params['phif2_kk_BW_BW_theta']
    )
    data_u_kst2_r_kk_BW_BW = calculate_BW_BW(
        params['phi_mass'], params['phi_width'], data_phi_kk,
        params['u_kst2_r_kk_BW_BW_mass'], params['u_kst2_r_kk_BW_BW_width'], data_f_kk,
        data_u_kst2_r_kk, params['u_kst2_r_kk_BW_BW_const'], params['u_kst2_r_kk_BW_BW_theta']
    )
    data_u_kst2_l_kk_BW_BW = calculate_BW_BW(
        params['phi_mass'], params['phi_width'], data_phi_kk,
        params['u_kst2_l_kk_BW_BW_mass'], params['u_kst2_l_kk_BW_BW_width'], data_f_kk,
        data_u_kst2_l_kk, params['u_kst2_l_kk_BW_BW_const'], params['u_kst2_l_kk_BW_BW_theta']
    )
    component_data_phif0_kk_BW_flatte980 = component_BW_flatte980(
        params['phi_mass'], params['phi_width'], truth_phi_kk,
        params['phif0_kk_BW_flatte980_mass'], params['phif0_kk_BW_flatte980_g_kk'], params['phif0_kk_BW_flatte980_rg'], truth_f_kk,
        truth_phif0_kk, params['phif0_kk_BW_flatte980_const'], params['phif0_kk_BW_flatte980_theta']
    )
    component_data_phif0_kk_BW_BW = component_BW_BW(
        params['phi_mass'], params['phi_width'], truth_phi_kk,
        params['phif0_kk_BW_BW_mass'], params['phif0_kk_BW_BW_width'], truth_f_kk,
        truth_phif0_kk, params['phif0_kk_BW_BW_const'], params['phif0_kk_BW_BW_theta']
    )
    component_data_phif2_kk_BW_flatte1270 = component_BW_flatte1270(
        params['phi_mass'], params['phi_width'], truth_phi_kk,
        params['phif2_kk_BW_flatte1270_mass'], params['phif2_kk_BW_flatte1270_width'], truth_f_kk,
        truth_phif2_kk, params['phif2_kk_BW_flatte1270_const'], params['phif2_kk_BW_flatte1270_theta']
    )
    component_data_phif2_kk_BW_BW = component_BW_BW(
        params['phi_mass'], params['phi_width'], truth_phi_kk,
        params['phif2_kk_BW_BW_mass'], params['phif2_kk_BW_BW_width'], truth_f_kk,
        truth_phif2_kk, params['phif2_kk_BW_BW_const'], params['phif2_kk_BW_BW_theta']
    )
    component_data_u_kst2_r_kk_BW_BW = component_BW_BW(
        params['phi_mass'], params['phi_width'], truth_phi_kk,
        params['u_kst2_r_kk_BW_BW_mass'], params['u_kst2_r_kk_BW_BW_width'], truth_f_kk,
        truth_u_kst2_r_kk, params['u_kst2_r_kk_BW_BW_const'], params['u_kst2_r_kk_BW_BW_theta']
    )
    component_data_u_kst2_l_kk_BW_BW = component_BW_BW(
        params['phi_mass'], params['phi_width'], truth_phi_kk,
        params['u_kst2_l_kk_BW_BW_mass'], params['u_kst2_l_kk_BW_BW_width'], truth_f_kk,
        truth_u_kst2_l_kk, params['u_kst2_l_kk_BW_BW_const'], params['u_kst2_l_kk_BW_BW_theta']
    )
    sum_frac = np.sum(dplex_dabs(
        np.einsum("mljk->mjk", component_data_phif0_kk_BW_flatte980) +
        np.einsum("mljk->mjk", component_data_phif0_kk_BW_BW) +
        np.einsum("mljk->mjk", component_data_phif2_kk_BW_flatte1270) +
        np.einsum("mljk->mjk", component_data_phif2_kk_BW_BW) +
        np.einsum("mljk->mjk", component_data_u_kst2_r_kk_BW_BW) +
        np.einsum("mljk->mjk", component_data_u_kst2_l_kk_BW_BW)
    ))
    frac_phif0_flatte980 = np.sum(np.einsum("ljk->l", dplex_dabs(component_data_phif0_kk_BW_flatte980)) / sum_frac)
    frac_phif0_BW = np.sum(np.einsum("ljk->l", dplex_dabs(component_data_phif0_kk_BW_BW)) / sum_frac)
    frac_phif2_flatte1270 = np.sum(np.einsum("ljk->l", dplex_dabs(component_data_phif2_kk_BW_flatte1270)) / sum_frac)
    frac_phif2_BW = np.sum(np.einsum("ljk->l", dplex_dabs(component_data_phif2_kk_BW_BW)) / sum_frac)
    frac_u_kst2_r_BW = np.sum(np.einsum("ljk->l", dplex_dabs(component_data_u_kst2_r_kk_BW_BW)) / sum_frac)
    frac_u_kst2_l_BW = np.sum(np.einsum("ljk->l", dplex_dabs(component_data_u_kst2_l_kk_BW_BW)) / sum_frac)
    total_frac = frac_phif0_flatte980 + frac_phif0_BW + frac_phif2_flatte1270 + frac_phif2_BW + frac_u_kst2_r_BW + frac_u_kst2_l_BW
    step_function = np.power(total_frac - total_frac_kk, 2.0) * constraint_strength
    step_function = step_function + np.power(0.98 - args[0], 2) / np.power(10.0, 2) / 2.0
    step_function = step_function + np.power(1.704 - args[5], 2) / np.power(1.0, 2) / 2.0
    step_function = step_function + np.power(0.123 - args[6], 2) / np.power(1.0, 2) / 2.0
    step_function = step_function + np.power(1.2755 - args[11], 2) / np.power(1.0, 2) / 2.0
    step_function = step_function + np.power(0.1867 - args[12], 2) / np.power(1.0, 2) / 2.0
    step_function = step_function + np.power(1.517 - args[23], 2) / np.power(1.0, 2) / 2.0
    step_function = step_function + np.power(0.086 - args[24], 2) / np.power(1.0, 2) / 2.0
    step_function = step_function + np.power(2.157 - args[35], 2) / np.power(1.0, 2) / 2.0
    step_function = step_function + np.power(0.152 - args[36], 2) / np.power(1.0, 2) / 2.0
    step_function = step_function + np.power(2.345 - args[47], 2) / np.power(0.01, 2) / 2.0
    step_function = step_function + np.power(0.322 - args[48], 2) / np.power(1.0, 2) / 2.0
    step_function = step_function + np.power(2.47 - args[59], 2) / np.power(0.007, 2) / 2.0
    step_function = step_function + np.power(0.075 - args[60], 2) / np.power(0.011, 2) / 2.0
    step_function = step_function + np.power(2.1 - args[65], 2) / np.power(10.0, 2) / 2.0
    step_function = step_function + np.power(0.1 - args[66], 2) / np.power(10.0, 2) / 2.0
    step_function = step_function + np.power(1.819 - args[71], 2) / np.power(10.0, 2) / 2.0
    step_function = step_function + np.power(0.264 - args[72], 2) / np.power(10.0, 2) / 2.0
    step_function = step_function + np.power(2.247 - args[77], 2) / np.power(10.0, 2) / 2.0
    step_function = step_function + np.power(0.18 - args[78], 2) / np.power(10.0, 2) / 2.0
    total_amplitude = data_phif0_kk_BW_flatte980
    total_amplitude = total_amplitude + data_phif0_kk_BW_BW
    total_amplitude = total_amplitude + data_phif2_kk_BW_flatte1270
    total_amplitude = total_amplitude + data_phif2_kk_BW_BW
    total_amplitude = total_amplitude + data_u_kst2_r_kk_BW_BW
    total_amplitude = total_amplitude + data_u_kst2_l_kk_BW_BW
    likelihood = -np.sum(np.log(np.sum(dplex_dabs(total_amplitude), axis=1))) + step_function
    return likelihood

def mc_likelihood_kk(args):
    params = extract_parameters(args)
    total_mc = calculate_BW_flatte980(
        params['phi_mass'], params['phi_width'], mc_phi_kk,
        params['phif0_kk_BW_flatte980_mass'], params['phif0_kk_BW_flatte980_g_kk'], params['phif0_kk_BW_flatte980_rg'], mc_f_kk,
        mc_phif0_kk, params['phif0_kk_BW_flatte980_const'], params['phif0_kk_BW_flatte980_theta']
    )
    total_mc = total_mc + calculate_BW_BW(
        params['phi_mass'], params['phi_width'], mc_phi_kk,
        params['phif0_kk_BW_BW_mass'], params['phif0_kk_BW_BW_width'], mc_f_kk,
        mc_phif0_kk, params['phif0_kk_BW_BW_const'], params['phif0_kk_BW_BW_theta']
    )
    total_mc = total_mc + calculate_BW_flatte1270(
        params['phi_mass'], params['phi_width'], mc_phi_kk,
        params['phif2_kk_BW_flatte1270_mass'], params['phif2_kk_BW_flatte1270_width'], mc_f_kk,
        mc_phif2_kk, params['phif2_kk_BW_flatte1270_const'], params['phif2_kk_BW_flatte1270_theta']
    )
    total_mc = total_mc + calculate_BW_BW(
        params['phi_mass'], params['phi_width'], mc_phi_kk,
        params['phif2_kk_BW_BW_mass'], params['phif2_kk_BW_BW_width'], mc_f_kk,
        mc_phif2_kk, params['phif2_kk_BW_BW_const'], params['phif2_kk_BW_BW_theta']
    )
    total_mc = total_mc + calculate_BW_BW(
        params['phi_mass'], params['phi_width'], mc_phi_kk,
        params['u_kst2_r_kk_BW_BW_mass'], params['u_kst2_r_kk_BW_BW_width'], mc_f_kk,
        mc_u_kst2_r_kk, params['u_kst2_r_kk_BW_BW_const'], params['u_kst2_r_kk_BW_BW_theta']
    )
    total_mc = total_mc + calculate_BW_BW(
        params['phi_mass'], params['phi_width'], mc_phi_kk,
        params['u_kst2_l_kk_BW_BW_mass'], params['u_kst2_l_kk_BW_BW_width'], mc_f_kk,
        mc_u_kst2_l_kk, params['u_kst2_l_kk_BW_BW_const'], params['u_kst2_l_kk_BW_BW_theta']
    )
    return np.mean(np.sum(dplex_dabs(total_mc), axis=1))


def combined_likelihood(args):
    """组合似然函数: data_likelihood + datasize * log(mc_likelihood)"""
    data_lh = data_likelihood_kk(args)
    mc_lh = mc_likelihood_kk(args)
    combined_lh = data_lh + data_size * np.log(mc_lh)
    return combined_lh

def hvp_combined_likelihood(args, vector):
    """计算Hessian-vector product for combined likelihood"""
    return jvp(grad(combined_likelihood), [args], [vector])[1]



data = load_data()
data = normalize_data(data)
jax_data = prepare_data_for_jax(data)

data_phi_kk = jax_data['data_phi_kk']
data_f_kk = jax_data['data_f_kk']
data_kst2_124_kk = jax_data['data_kst2_124_kk']
data_kst2_123_kk = jax_data['data_kst2_123_kk']
data_phif0_kk = jax_data['data_phif0_kk']
data_phif2_kk = jax_data['data_phif2_kk']
data_u_kst2_r_kk = jax_data['data_u_kst2_r_kk']
data_u_kst2_l_kk = jax_data['data_u_kst2_l_kk']

mc_phi_kk = jax_data['mc_phi_kk']
mc_f_kk = jax_data['mc_f_kk']
mc_kst2_124_kk = jax_data['mc_kst2_124_kk']
mc_kst2_123_kk = jax_data['mc_kst2_123_kk']
mc_phif0_kk = jax_data['mc_phif0_kk']
mc_phif2_kk = jax_data['mc_phif2_kk']
mc_u_kst2_r_kk = jax_data['mc_u_kst2_r_kk']
mc_u_kst2_l_kk = jax_data['mc_u_kst2_l_kk']

truth_phi_kk = jax_data['truth_phi_kk']
truth_f_kk = jax_data['truth_f_kk']
truth_kst2_124_kk = jax_data['truth_kst2_124_kk']
truth_kst2_123_kk = jax_data['truth_kst2_123_kk']
truth_phif0_kk = jax_data['truth_phif0_kk']
truth_phif2_kk = jax_data['truth_phif2_kk']
truth_u_kst2_r_kk = jax_data['truth_u_kst2_r_kk']
truth_u_kst2_l_kk = jax_data['truth_u_kst2_l_kk']

wt_data_kk = jax_data['wt_data_kk']

data_size = len(data_phi_kk)

if __name__  == "__main__":
    """使用Newton-CG方法和HVP的拟合函数"""
    logger = setup_logging()
    logger.info("开始HVP优化版PWA拟合（Newton-CG方法）")

    import jax.numpy as np

    config.update("jax_enable_x64", True)

    constraint_strength = 0.0
    total_frac_kk = 1.0
    args_list = make_initial_args()

    logger.info("编译JAX函数（HVP版本）...")
    jit_likelihood = jit(combined_likelihood)
    jit_grad = jit(grad(combined_likelihood))
    jit_hvp = jit(hvp_combined_likelihood)

    test_result = jit_likelihood(args_list)
    logger.info(f"初始似然值: {test_result}")

    test_vector = onp.ones_like(args_list)
    test_hvp = jit_hvp(args_list, test_vector)
    logger.info(f"HVP测试完成，结果形状: {test_hvp.shape}")

    def my_callback(x):
        current_likelihood = jit_likelihood(x)
        logger.info(f"当前似然值: {current_likelihood}")

    def hessp(x, p):
        return onp.array(jit_hvp(x, p))

    logger.info("开始优化（Newton-CG + HVP）...")
    start_time = time.time()

    result = minimize(
        fun=lambda x: float(jit_likelihood(x)),
        x0=args_list,
        jac=lambda x: onp.array(jit_grad(x)),
        hessp=hessp,
        method="Newton-CG",
        callback=my_callback,
        options={"disp": False, "xtol": 1e-8}
    )

    end_time = time.time()

    logger.info("="*50)
    logger.info(f"HVP优化完成!")
    logger.info(f"成功: {result.success}")
    logger.info(f"最终似然值: {result.fun}")
    logger.info(f"迭代次数: {result.nit}")
    logger.info(f"函数调用次数: {result.nfev}")
    logger.info(f"梯度调用次数: {result.njev}")
    logger.info(f"Hessian调用次数: {result.nhev}")
    logger.info(f"优化时间: {end_time - start_time:.2f} 秒")
    logger.info(f"优化信息: {result.message}")
    logger.info("="*50)

    logger.info("计算参数误差（Hessian逆矩阵）...")
    args_size = args_list.shape[0]
    hessian_matrix = onp.zeros([args_size, args_size])
    for i in range(args_size):
        v = onp.zeros(args_size)
        v[i] = 1.0
        hessian_matrix[:, i] = onp.array(jit_hvp(result.x, v))
    ferror = onp.sqrt(onp.diag(onp.linalg.inv(hessian_matrix)))
    logger.info(f"误差计算完成")

    os.makedirs("output/fit", exist_ok=True)
    onp.save("output/fit/fit_result_values.npy", result.x)
    onp.save("output/fit/fit_result_errors.npy", ferror)
    logger.info("参数已保存至 output/fit/fit_result_values.npy")

    save_results(result.x, ferror, "output/fit/fit_result_config.toml")
    logger.info("配置已保存至 output/fit/fit_result_config.toml")