[header]
IP = "192.168.1.13"
PORT = 12345 
# ssh用户名，用于同步docker image与work-dir
# 需要配置免密码登录
Username = "nvidia"
# ETH_IF --- NCCL_SOCKET_IFNAME in container env
#ETH_IF="enp1s0f0np0"
# IB_IF --- NCCL_IB_HCA in container env
IB_IF="rocep1s0f0,roceP2p1s0f0"


[[worker]]
IP = "192.168.1.12"
#ETH_IF="enp1s0f0np0"
# 由于spark上一个connectx7接口对应linux系统中两个设备
IB_IF="rocep1s0f0,roceP2p1s0f0"
Username = "nvidia"


[container]
image = "jax:latest"
container = "kkfit"
env = [
    "NCCL_DEBUG=VERSION", 
    "NCCL_IGNORE_CPU_AFFINITY=1",
]